### ISSUE TITLE
Changes for Bioconductor submission

### ISSUE THREAD

**Issue by LTLA** [LTLA/SingleR#1]
Tagging @dviraran, @dtm2451.

# Algorithm

I have tried to keep the output as close as possible to the original. A few minor changes have been made to improve speed:

- The quantile is rounded to the nearest cell. This should have negligible impact on the scores but allows us to use a different algorithm to compute the quantile, which should greatly improve speed. Still quadratic, but it should have a much better scaling.
- The fine-tuning step for `genes="sd"` does not use the 500 gene cut-off, instead just taking all genes with standard deviations above the SD threshold. This was performed simply to make it easier to implement (and also to make it consistent with the initial marker gene detection prior to fine-tuning). Note that ease of implementation is important; C++ gets pretty intense.

In my hands, the original `SingleR` on the pancreas data example takes 500 seconds on 7 cores, while this modified `SingleR` takes 125 seconds on 1 core. It should be possible to achieve greater speed by parallelizing the fine-tuning here, I just haven't gotten around to it.

# Functions

As discussed, I have removed all functions except the most critical ones. This made the entire package much simpler to test and document, and it avoids problems with feature creep. 

- Some of the visualization functions belong somewhere else, e.g., Dittoseq?
- Some of the data structure-related functions are no longer necessary if we're using the `SingleCellExperiment` as the data container. Note that this doesn't preclude use with non-SCE-based workflows (e.g.,  _Seurat_), the functions will happily accept raw count/expression matrices.
- I wasn't sure what the SingScore and GSVA-related functions were meant for, so I took them out for the time being.

(IMO, feature creep is a real problem - looking at https://github.com/dviraran/SingleR/issues suggests that most of the issues have nothing to do with the `SingleR()` function! Many of them seem to be problems with converting to/from data structures; better to shift the responsibility for answering those questions to the maintainers who defined those data structures.)

In addition, the `SingleR()` function itself can be called by advanced users as two separate components, `trainSingleR()` and `classifySingleR()`. This allows the training cost (i.e., marker gene detection, setting up the nearest neighbor indices) to be paid once for multiple rounds of classification with different test datasets.

# Documentation

There's now a lot more of it, concentrated in fewer functions. The vignette has also been stripped down so that it will run within the 5 minute timeframe for Bioconductor builds.

# Unit tests

Now there are some.

# Data

This is the last remaining outstanding issue (we should open a new Issue to discuss this). The various reference datasets have been stripped out to reduce the repository size (cloning took minutes and 1 GB of space!) and the package size. Instead, I propose that data be stored in Bioconductor's _ExperimentHub_, where it is pulled down as needed by each user and cached locally. This separates code from data, reduces the package/repo size, and avoids cluttering the user's R installation with reference datasets they might not ever use.

To put data in _ExperimentHub_, we need to describe how the reference datasets were obtained. I don't want to have an entire treatise on scraping GEO for bulk RNA-seq data, but we should be able to point interested parties to a repository of code that did it. Is that code somewhere in the NI paper? If so, our description can simply point to the NI paper, pull objects from the `data` directory of https://github.com/dviraran/SingleR, and clean them up for EHub upload.

# To do:

- Need to parallelize various functions with _BiocParallel_. This allows the same type of parallelization as `mcapply`, but also allows users to parallelize with SNOW, Slurm, LSF, etc. 
- Need to add some functions in _BiocNeighbors_ to reduce memory usage and make `SingleR()` slightly faster. Specifically, this avoids allocating a matrix of distances to neighbors when only the distance to the `k`th neighbor is of interest.

**Comment by j-andrews7** [comment]
As another (less tidy/elegant, but likely quicker) solution for the Data issue, you could just store it in another repo and use a function to pull it as needed. Something like:

```r
#' Retrieve SingleR reference datasets from Github.
#'
#' \code{GetSinglerRef} retrieves \code{SingleR} reference datasets from Github. 
#'
#' @param dataset String referring to SingleR reference dataset to retrieve. 
#'   Options include:
#'   \itemize{
#'     \item "hpca"
#'     \item "blueprint_encode"
#'     \item "immgen"
#'     \item "mouse.rnaseq"
#'   }
#' @return SingleR reference dataset.
#'
#' @importFrom curl curl_download
#'
#' @export
#'
GetSinglerRef <- function(dataset = "hpca") {
	opts <- c("hpca", "blueprint_encode", "immgen", "mouse.rnaseq")
	if (!(dataset %in% opts)) {
		stop("Invalid SingleR reference set. Valid options are 'hpca',", 
			"'blueprint_encode', 'immgen', or 'mouse.rnaseq'")
	}
	base.url <- "https://github.com/dviraran/SingleR/blob/master/data/"
	url.tail <- ".rda?raw=true"

	tmp <- tempfile()
	curl_download(paste0(base.url, dataset, url.tail), tmp)

	# This could be less gross if rds files were used instead.
	load(tmp)
	ref.set <- eval(as.name(paste0(dataset)))
	
	return(ref.set)
}
```

This would still allow users to save them locally if desired, and hits all of your other points fairly well too. Will be good to see this in Bioconductor.

**Comment by LTLA** [comment]
Yes, this would be the currently most expedient solution while the ExperimentHub solution is in progress. If you make a PR, I'd be happy to consider it. Just some points if you do:

- Follow BioC function naming conventions, see the commentary in #2.
- Use _BiocFileCache_ to cache each download on first use:

```r
bfc <- BiocFileCache(ask=FALSE)
ref <- bfcrpath(bfc, "my_url_here")
```

**Comment by LTLA** [comment]
Guess this is done, so I'm closing it.
