### ISSUE TITLE
Question regarding normalization

### ISSUE THREAD

**Issue by MwrulesC** [LTLA/SingleR#104]
I was going through the vignettes for the package, and it mentioned that the it uses log normalized expression matrices. I recall while looking at the vignette for an earlier development version of the package, it uses the steps ```computeSumFactors``` and ```normalize``` prior to running ```logNormCounts```. However, in the current vignette it directly performs ```logNormCounts```. I was wondering if there is a reason why these steps are no longer included.

Thanks.

**Comment by dtm2451** [comment]
They aren;'t included explicitly because the `logNormCounts` function performs these size factor and normalization steps internally.

**Comment by LTLA** [comment]
I'll give my best guess as to why it changed:

- Switched from `normalize()` to `logNormCounts()` as the former was deprecated from **scater**. The reason for this deprecation was that `normalize()` meant too many things to different people, so it was better to be explicit. 
- Probably cut out `computeSumFactors()` to speed up the vignette so we could fit in under the 5 minute limit on the package CHECK process on the Bioconductor build machines.

As @dtm2451 said, `logNormCounts()` will compute size factors and then the log-normalized expression values, the only difference between before and after is that it's not using the `computeSumFactors()` size factors. The difference probably won't matter much here, you can read the last paragraph [here](https://osca.bioconductor.org/normalization.html#normalization-by-deconvolution). And it won't matter at all for the assignments if you're doing this on the test data, it only matters for the reference data, and even then only for marker detection.

**Comment by MwrulesC** [comment]
Thank you both for your answers, that was really helpful.
