### ISSUE TITLE
Adding annotations

### ISSUE THREAD

**Issue by AteeqKhaliq** [LTLA/SingleR#110]
Hi,
We have created singleR object without giving annotations txt file, can we add annotations for the cells to the singleR object without re-running the computationally intensive steps like fine.tune=T again?
are they're a way to do this without re-running the following code again
We have ~ 50000 Cells and two categories (Normal Vs Diseased)

singler_new <- CreateSinglerSeuratObject(counts = counts, project.name = '', species = "Human", annot= NULL, min.genes = 500, min.cells = 2, npca = 10, technology = "X10", citation = "", ref.list = list(), normalize.gene.length = F, variable.genes = "de", fine.tune = T, do.signatures = T, do.main.types = T, reduce.file.size = T, numCores = 8)

to this

singler_new <- CreateSinglerSeuratObject(counts = counts, project.name = '', species = "Human", annot= "colnames.count.txt", min.genes = 500, min.cells = 2, npca = 10, technology = "X10", citation = "", ref.list = list(), normalize.gene.length = F, variable.genes = "de", fine.tune = T, do.signatures = T, do.main.types = T, reduce.file.size = T, numCores = 4)

Regards,
Jack

**Comment by j-andrews7** [comment]
Please read the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/SingleR/inst/doc/SingleR.html) and consult the [reference manual](https://bioconductor.org/packages/release/bioc/manuals/SingleR/man/SingleR.pdf) for this package, as it has been altered to be easier to use and much, much faster. I don't know what the old version did with the annotations file (presumably just metadata?), but the new version spits out a table of predictions, from which you can slap the labels on your Seurat, SCE, etc object as needed.

**Comment by j-andrews7** [comment]
I'm going to assume your issue was solved, feel free to reopen if not.
