### ISSUE TITLE
SingleR results and Seurat object

### ISSUE THREAD

**Issue by ashiqmb** [LTLA/SingleR#113]
Hi Aaron and team, 

After obtaining results from SingleR. How can we extract a new Seurat object created by SingleR? 
I can see a new Seurat object  in SingleR results but don’t know how to subset it.
Many thanks 
Duke

**Comment by j-andrews7** [comment]
SingleR does not create a new Seurat object - it is workflow agnostic. Please ensure you are using the [Bioconductor](https://bioconductor.org/packages/release/bioc/html/SingleR.html) version of the package and check out the [vignette](https://bioconductor.org/packages/release/bioc/vignettes/SingleR/inst/doc/SingleR.html) for example usage.

In general, once predictions are returned, they can be added to a Seurat object as so:

seurat.obj[["SingleR.labels"]] <- singler.results$labels

# Or if `method="cluster"` was used:
seurat.obj[["SingleR.cluster.labels"]] <- 
        singler.results$labels[match(seurat.obj[[]][["my.input.clusters"]], rownames(singler.results))]

**Comment by j-andrews7** [comment]
I am going to assume your issue has been resolved, feel free to reopen if not.

**Comment by jcook-ucsf** [comment]
I'm a little confused by what i'm supposed to replace "my.input.clusters" with, a concatenated list of cluster numbers?

**Comment by dtm2451** [comment]
I gave a separate code option in the new issue that you opened @jcook-ucsf, which should also work, and may be faster.

But the code here, what you would give for "my.input.clusters" is the name of the metadata slot that holds your clustering info.  So, I believe `"seurat_clusters"` in your case. With Seurat, there can be many odd syntax options, but ultimately, this entire bit `seurat.obj[[]][["my.input.clusters"]]` should be the same per-cell values that were given to SingleR(clusters = <this_data>).
