### ISSUE TITLE
Create my own reference with RNAseq data

### ISSUE THREAD

**Issue by AnaisJulien** [LTLA/SingleR#115]
Dear all, 
I have a RNAseq data set with sorted populations and I would like to use it as reference to identify my cells within single cell data set. 
I try to generate a SummarizedExperiment, but I don't get log count into the assay of my SE. I have S3:dataframe instead. 

Do you know I to fix that ? 
If you have another method to use the RNAseq data as reference that's fine also !

Thank you !

**Comment by j-andrews7** [comment]
You need two things to create your own reference - a log-transformed counts matrix where rows are genes and columns are samples, and a character vector of labels that have an entry for each sample. These arguments should be supplied to `ref` and `labels` respectively in your `SingleR` call. It's not required that you use a `SummarizedExperiment`, though it can be convenient if you want to store your expression data and labels in the same object.

The `SingleR` function documentation is pretty comprehensive and can be accessed via `?SingleR`.

**Comment by AnaisJulien** [comment]
Thank j-andrews7 !

However, I still have a problem. I can find the common genes, but when I call SingleR function, I get this error: 
> pred.test <- SingleR(test = Tsukui_test, ref = "Glast", labels = x)
Error in FUN(X[[i]], ...) : 'ref' must have row names

Do you know why ? 

Thank

**Comment by AnaisJulien** [comment]
Thank j-andrews7 ! 

Perfect solution!
