### ISSUE TITLE
Feature Request: Extension to scATAC-seq data?

### ISSUE THREAD

**Issue by ONeillMB1** [LTLA/SingleR#120]
Thanks for developing this! 
Any plans to extend to scATAC-seq data?

**Comment by LTLA** [comment]
The algorithm doesn't care where the data comes from, as long as the references are appropriate. 

Now, getting appropriate references is the more difficult challenge. I don't work much with ATAC-seq data, but I used to do a lot of work with ChIP-seq data, and one obvious challenge is the fact that the features (peaks) need to be empirically detected and are not the same across experiments. In this case, everyone would have to agree on what features the references should have. Even the simplest method of creating bins would require a decision on a "reasonable" bin size.

**Comment by dtm2451** [comment]
While untested for this purpose, there's no reason SingleR *couldn't* work already. As @LTLA said, SingleR learns markers empirically from the reference provided, so if you have an annotated ATACseq reference set, with regions that are consistent between the `ref` and `test` data, theoretically, it should work.

**Comment by dtm2451** [comment]
Doubling back, @ONeillMB1, if you can generate your `test` & `ref` data with compatible bins, I'm quite interested to hear how SingleR works for you. It would be really great if ATAC data can be deemed "officially" supported!

**Comment by dtm2451** [comment]
closing as the issue seems resolved, or at least out of our hands.
