### ISSUE TITLE
Functions in the previous SingleR version (SingleR1.0) 

### ISSUE THREAD

**Issue by Sa753** [LTLA/SingleR#124]
Hi Aaron,

There were quite nice functions in the previous version of SingleR in 2019 especially
related to plotting heat maps and TSNE/UMAP on Seurat clusters. Unfortunately, when I tried using any of those functions, I can't find them anymore. 

Is there anyway to restore that please?

Thanks

**Comment by j-andrews7** [comment]
The [vignette](https://bioconductor.org/packages/release/bioc/vignettes/SingleR/inst/doc/SingleR.html) and [manual](https://bioconductor.org/packages/release/bioc/manuals/SingleR/man/SingleR.pdf) show how you can create heatmaps from the results. The [README](https://github.com/LTLA/SingleR) shows how you can add results back to your Seurat objects, at which point they can be plotted like any other metadata variable:

seurat.obj[["SingleR.labels"]] <- singler.results$labels

# Or if `method="cluster"` was used:
seurat.obj[["SingleR.cluster.labels"]] <- 
        singler.results$labels[match(seurat.obj[[]][["my.input.clusters"]], rownames(singler.results))]

**Comment by Sa753** [comment]
Thank you so much.
