### ISSUE TITLE
About non-corrected assay RNA assay counts slot generated by seurat integrated workflow using for  old singler version to annotate cell issues

### ISSUE THREAD

**Issue by honghh2018** [LTLA/SingleR#128]
Hi Developer All,
     Recently, it seem to me  that integrated seurat counts of RNA slot  was not corrected yet and origin data, which make me confuse about data whether should take sample-corrected firstly or not when runing singler?
     Any advice would be grateful

**Comment by dtm2451** [comment]
The "RNA" slot is typically better than the "integrated" slot, and either raw or normalized counts data work fine for `test`. (`ref` should be normalized, but `test` does not need to be.)

Not sure if that answers your question?

**Comment by dtm2451** [comment]
closing as I think this is resolved. Feel free to open a new issue if question(s) remain.
