### ISSUE TITLE
Can't we feed clusters identified by Seurat to SingleR?

### ISSUE THREAD

**Issue by biobug16** [LTLA/SingleR#135]
Hi 
I am interested to use SingleR and want to predict cell types based on the clusters identified by Seurat.

I have also used earlier version of SingleR, but it seems the newer version or the one maintained as bioconductor package do not support the Seurat's clusters. As I tried following command:
`singler_hpca=SingleR(test = wt.list.integrated, ref = hpca.se, labels = hpca.se$label.main, method = "cluster",fine.tune = FALSE,clusters =wt.list.integrated$seurat_clusters)`
but got a warning:
```
Warning: The following arguments are not used: droplusters =wt.list.integrated$seurat_clusters
Error in CellsByIdentities(object = object, cells = cells) : 
  Cannot find cells provided
```

Please correct me if I am missing something here.

Thanks

**Comment by dtm2451** [comment]
1. Is `wt.list.integrated` a Seurat or SCE?  If it's a Seurat, you should provide `test = GetAssayData(wt.list.integrated, assay = "RNA")` & `clusters = Idents(wt.list.integrated)`.
2. Not sure what the initial not used `droplusters` argument warning is... is this perhaps actually an error coming from code with that typo in place of the `clusters` argument?

**Comment by LTLA** [comment]
Session information?

**Comment by dtm2451** [comment]
Have you resolved this issue on your own @biobug16 ?

It seems to me that your issue may have been a code typo or something simple to fix, but, if you would like our help with diagnosing this issue, you will need you to respond to our requests for more details.

**Comment by biobug16** [comment]
I have resolved the issue.
Thanks for your help.
