### ISSUE TITLE
Multiple references with some references having 1 or 2 labels. 

### ISSUE THREAD

**Issue by danhtruong** [LTLA/SingleR#137]
Hi,

Thanks for the great and simple package for annotation. This package seems to be the fastest with the least parameters to take into consideration. This may be an issue similar to #122.  

Now for my question. I have tested out single references and multiple references extensively and I have noticed something that may or may not affect the algorithm. 

For references with 1 or 2 labels, the labels are compared for DE genes/markers which are then used to annotate your test set. I have noticed that if the 2 labels are from cells that are very closely similar, you get a very nuanced set of DEs that may be too specific to match with the test set. This is especially true if your other reference sets contain broader labels that would score higher than the specific labels from the small reference set. I don't know if I missed this in the documentation, but how are labels between references compared? Is it just the higher of the two within their own reference? 

Assuming that is the case, should I just combine all my references into a single reference set (with intersection of genes of course)? In doing so, would it enable better identified DEs? 

Thanks,
Danh

**Comment by LTLA** [comment]
The [corresponding chapter of the book](https://ltla.github.io/SingleRBook/using-multiple-references.html) may be relevant. 

As for the last question: it depends on whether you're willing to accept the batch effects that will be present in the comparisons between the individual references. If you anticipate that the batch effects are less than the biological differences between the cell types in the different references, then sure, you can just stick them all together.

**Comment by danhtruong** [comment]
Thanks. I will take a look at the book. I did not know this was released recently. I agree about the batch effects and it will be something to consider.
