### ISSUE TITLE
best practice for shorter names

### ISSUE THREAD

**Issue by wfma** [LTLA/SingleR#140]
Hi!

I used singleR to identify cells in my dataset, which worked great. I was wondering what is the best practice to rename cells that have really long names, e.g. "Smooth_muscle_cells" to simply "SMC" so the graphs could come out better.

I used dyplr 'recode' function and it seemed to work, but unsure if there is a better way:

`seuratobject@meta.data[["SingleR.calls"]] <- recode(seuratobject@meta.data[["SingleR.calls"]], Smooth_muscle_cells = "SMC")
`

Thank you,
Wei

**Comment by LTLA** [comment]
I don't have much advice for choosing shorter names; the trade-off between shortness and informativeness seems like it would be a decision on your part. Certainly I wouldn't have any idea what "SMCs" are, so I personally would not abbreviate it.

If you have a partial set of remappings as a named character vector, then the `dplyr::recode` approach is probably the approach that involves the least typing. Whether this is the "best" approach is another matter; in a package context, it is such a trivial operation that I would just write my own code to avoid having to pull in any **tidyverse** dependencies.

If you have a full set of remappings (i.e., all existing terms have a corresponding abbreviation), then you can just do:

```r
c(Smooth_muscle_cells = "SMC", ... mappings for all other cell types)[existing_singleR_labels]
```

**Comment by wfma** [comment]
I see, thank you for the quick reply!
Wei
