### ISSUE TITLE
How to cite the new version of SingleR

### ISSUE THREAD

**Issue by davidepisu** [LTLA/SingleR#143]
Hi everyone,

I'm writing a manuscript and I used the new version of SingleR to generate some heatmaps with my clusters.
It is my understanding that the only paper out about SingleR is the one from Nature Immunology (2019). However that paper refers to the old version of the software that is not supported anymore.
So I'm wondering, should I cite the Nature Immunology paper or you guys have a new manuscript I would need to cite?

Thank you.

**Comment by j-andrews7** [comment]
The method is the same as the original, so that should still be cited. There's a possibility of something being written up for the software itself, but for the time being, the Nature Immunology paper is the proper choice.

**Comment by davidepisu** [comment]
Sounds good. Thank you

**Comment by LTLA** [comment]
I'll just add that the core algorithm in here is the same as that in the original package, and I'm reasonably confident that it gives the same results. Well, maybe not exactly the same (e.g., changed how we handled `NA`s) but close. So it is perfectly fine to cite Dvir's paper, though best to mention that you're using the Bioconductor version of the package.

In an ideal world, we would write up a little biorXiv paper describing some of the improvements (e.g., speed, multi-reference handling, aggregation). But writing is boring and I can't ~trick~ find any ~suckers~ grad students to do it.
