### ISSUE TITLE
failed to load reference data

### ISSUE THREAD

**Issue by RuixiangLiu01** [LTLA/SingleR#147]
Hi, I get a problem when loading the reference data
![image](https://user-images.githubusercontent.com/37862626/94001438-18885e00-fdcb-11ea-8e55-0e8df40b087f.png)
how can I solve this?Thanks!

**Comment by dtm2451** [comment]
It's hard to troubleshoot something without knowing the error message. Would you be able to translate the non-English characters?

**Comment by LTLA** [comment]
The third-from-last character is "person", and that's all I know.

**Comment by RuixiangLiu01** [comment]
> It's hard to troubleshoot something without knowing the error message. Would you be able to translate the non-English characters?

error message says "no such input format"

**Comment by RuixiangLiu01** [comment]
> The third-from-last character is "person", and that's all I know.

I am considering whether the file I downloaded is incomplete

**Comment by LTLA** [comment]
Did this get fixed?

**Comment by j-andrews7** [comment]
Closing this to keep things tidy. Feel free to reopen if you continue running into this error and can provide more info.
