### ISSUE TITLE
Retrieving a list of marker genes which were used assign cell type labels to clusters 

### ISSUE THREAD

**Issue by jdd1e16** [LTLA/SingleR#148]
Hello, I am using SingleR within python with the BlueprintEncodeData reference dataset. I am successfully getting my predicted cell type annotations for my distinct clusters. I was just wondering however, if there is a way in which i could retrieve a list of genes which are being used to assign the cell type labels to each cluster?
Thanks in advance!
James

**Comment by LTLA** [comment]
Sure, you should be able to fish it out from the `metadata` of the output `DataFrame`. Note that, by default,  markers are defined in a pairwise manner, i.e., which genes are upregulated in one label compared to each other label; this is why you get a list of lists of character vectors.

**Comment by jdd1e16** [comment]
Thank you very much!
