### ISSUE TITLE
Check for `ref` format, do not allow data.frame

### ISSUE THREAD

**Issue by ATpoint** [LTLA/SingleR#150]
Suggest that a check is implemented to exit right away if `ref` is a data.frame rather than a sce or matrix. 
Reason (assuming that the mock data from `examples` are loaded):

```
# ok
SingleR(test, as.matrix(assay(ref, "logcounts")), labels=ref$label)

# this one gives => Error in FUN(X[[i]], ...) : 'ref' must have row names
SingleR(test, data.frame(assay(ref, "logcounts")), labels=ref$label) 

# rownames are present
head(rownames(data.frame(assay(ref, "logcounts"))))
[1] "GENE_1" "GENE_2" "GENE_3" "GENE_4" "GENE_5" "GENE_6"
```
SingleR-v1.2.4

So better not allow data.frame right away or fix the reason for the rownames not being found. Sure, it is somewhat pebkac because the manual clearly says `ref` must be a sce or matrix but it still took me almost 30' to find out that the ref format was the problem here. Thanks!

**Comment by LTLA** [comment]
It is done. Just easier to make it work with `data.frame`s off the bat, so there you go.
