### ISSUE TITLE
fail to fetch the reference data

### ISSUE THREAD

**Issue by wu-yc** [LTLA/SingleR#151]
My server is located in China. I have tried to download the reference file in three different servers, but it always fails.
 
It always gives those errors,

> se <- MonacoImmuneData()
snapshotDate(): 2019-10-22
see ?SingleR and browseVignettes('SingleR') for documentation
loading from cache
Error: failed to load resource
  name: EH3100
  title: Monaco Immune Cell RNA-seq logcounts
  reason: error reading from connection

or,

> se <- MonacoImmuneData()
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: [experimenthub.bioconductor.org] Resolving timed out after 10000 milliseconds

Thanks for your support!

**Comment by LTLA** [comment]
Throwing this to @lshep. 

This probably goes into the increasingly big folder of "China-S3 connection problems". I wonder whether this is a general problem for all attempts to connect to S3 from users behind the Great Firewall, or whether there is something specific to the ExperimentHub configuration. I can't find much literature on the topic, I guess transnational organizations avoid this by having a Chinese mirror.

**Comment by wu-yc** [comment]
@LTLA Thanks for your fast reply.

Can I download the reference file manually and copy it to SingleR working directory? My server cannot reach the aws, but my computer can.

**Comment by LTLA** [comment]
It... might be possible, with enough trickery. First, if your computer can reach AWS, you should be able to do:

```r
library(ExperimentHub)
setExperimentHubOption("CACHE", value="hub")
dir.create("hub")

library(SingleR)
sce <- MonacoImmuneData()
```

Then, copy the entire `hub` directory over to the server with the usual methods, e.g., `scp` or whatever you like to use.

On the server side, it should then be a simple matter of doing:

```r
library(ExperimentHub)
setExperimentHubOption("CACHE", value="hub") # set this to the absolute path where you copied 'hub'. 

library(SingleR)
sce <- MonacoImmuneData()
```

Definitely not a pretty process, but oh well.

**Comment by wu-yc** [comment]
@LTLA Thank you very much for the continued support. It finally works!
