### ISSUE TITLE
SingleR use kmeans to 

### ISSUE THREAD

**Issue by zznx** [LTLA/SingleR#156]
hello 
SingleR used kmeans to classify test or ref. What role does ref play?   thank you

**Comment by dtm2451** [comment]
Short answer: it uses ref.

Long answer: Github issues are not a place to ask for information that you can get from ANY of the packages documentation.  Like I'm fairly certain this is even in the package's description.  It's certainly in `?SingleR` & the vignette.  You need to do at least some of your own work before coming here.

**Comment by zznx** [comment]
I'm sorry I didn't describe the problem clearly
I found the following code, so I thought I'd classify test instead of ref  ,thank you very much
```
> example(SingleR)

SinglR> # Mocking up data with log-normalized expression values:
SinglR> ref <- .mockRefData()

SinglR> test <- .mockTestData(ref)

SinglR> ref <- scuttle::logNormCounts(ref)

SinglR> test <- scuttle::logNormCounts(test)

SinglR> # Running the classification with different options:
SinglR> pred <- SingleR(test, ref, labels=ref$label)

SinglR> table(predicted=pred$labels, truth=test$label)
         truth
predicted  A  B  C  D  E
        A 25  0  0  0  0
        B  1 16  0  0  0
        C  0  0 25  0  0
        D  0  0  0 17  0
        E  0  0  0  1 15

SinglR> k.out<- kmeans(t(assay(test, "logcounts")), center=5) # mock up a clustering

SinglR> pred2 <- SingleR(test, ref, labels=ref$label, clusters=k.out$cluster) 

SinglR> table(predicted=pred2$labels, cluster=rownames(pred2))
         cluster
predicted 1 2 3 4 5
        A 0 0 0 0 1
        B 1 0 0 0 0
        C 0 1 0 0 0
        D 0 0 1 1 0

```

**Comment by zznx** [comment]
@dtm2451      Is that right?

**Comment by zznx** [comment]
[https://github.com/LTLA/SingleR/issues/53#issue-516683269](url)
I have no more questions for the moment. Thank you very much
