### ISSUE TITLE
Error while loading BlueprintEncodeData

### ISSUE THREAD

**Issue by parvathisudha** [LTLA/SingleR#158]
Hi,

I am getting an error while loading the data. SingleR and celldex were installed. 

`ref <- BlueprintEncodeData()`

Error:
snapshotDate(): 2020-04-27
 Error in .local(x, i, j = j, ...) : 'i' must be length 1 

Trace back:
6. stop("'i' must be length 1") 
5. .local(x, i, j = j, ...) 
4. hub[hub$rdatapath == file.path(host, ver, paste0(a, ".rds"))][[1]] 
3. hub[hub$rdatapath == file.path(host, ver, paste0(a, ".rds"))][[1]] at .active-rstudio-document#15
2. .create_se("blueprint_encode", version = list(logcounts = "1.0.0", 
    coldata = "1.2.0"), assays = "logcounts", rm.NA = rm.NA, 
    has.rowdata = FALSE, has.coldata = TRUE) at BlueprintEncodeData.R#56
1. BlueprintEncodeData() 

Debug:
> ref <- BlueprintEncodeData()
snapshotDate(): 2020-04-27
Error in .local(x, i, j = j, ...) : 'i' must be length 1
Called from: .local(x, i, j = j, ...)
Error during wrapup: unimplemented type (29) in 'eval'

Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Error during wrapup: INTEGER() can only be applied to a 'integer', not a 'unknown type #29'
Error: no more error handlers available (recursive errors?); invoking 'abort' restart
Browse[1]> 

> BiocManager::version()
[1] ‘3.11’
> BiocManager::valid()
[1] TRUE

R version 4.0.1 (2020-06-06)

Can you please help me to solve this issue?

**Comment by LTLA** [comment]
Not a great deal to say here: [**celldex**](http://bioconductor.org/packages/release/data/experiment/html/celldex.html) is only available in Bioconductor version 3.12 and onwards. So you need to update your BioC version if you want to use it. Otherwise, make sure you call `SingleR::BlueprintEncodeData()` if you want to keep using 3.11.

**Comment by parvathisudha** [comment]
Great! Thank you 👍
