### ISSUE TITLE
Basic Usage From Seurat Object?

### ISSUE THREAD

**Issue by bbimber** [LTLA/SingleR#16]
Hello,

I realize this package is evolving quickly, but I'm wondering if you can comment on this, which is trying ot start with a seurat object and run using HPCA data:

seuratObj <- readRDS(file = 'Test.seurat0.rds')
singler <- OOSAP:::GenerateSingleR(seuratObj = seuratObj0)

seuratObj <- readRDS(file = 'seurat.rds')
ref <- SingleR::HumanPrimaryCellAtlasData()

#Subset genes:
genesPresent <- intersect(rownames(seuratObj), rownames(ref))
ref <- ref[genesPresent,]
seuratObj <- seuratObj[genesPresent,]
sce <- as.SingleCellExperiment(seuratObj)

sce <- scater:::logNormCounts(sce, log = T)
pred <- SingleR::SingleR(test = sce, ref = ref, labels = ref$label.main, assay.type.ref = 'normcounts')

The HPCA data only contains the assay type 'normcounts', not 'logcounts' like the pred() default, so I assume we need to switch?  I'm transforming the raw seurat counts using logNormCounts(log=T), which puts them into the normcounts() assay slot.

Thanks for any help/suggestions.

**Comment by LTLA** [comment]
The `README` should now have some instructions on how to get it in from _Seurat_. Yes, there is some log transformation required, and we overlooked this (tagging @j-andrews7).

**Comment by j-andrews7** [comment]
Hmm, yeah, your current method will work fine, though we should make sure creating all of the reference datasets with `normcounts` instead of `logcounts` is accurate, as some of them are definitely log normalized (immgen, HPCA). @friedue, you're probably the expert on these datasets - any insight?

For reference:
```
> ref <- BlueprintEncodeData()
> sce.ref <- as(ref, "SingleCellExperiment")
> max(normcounts(sce.ref))
[1] 19.94247
> min(normcounts(sce.ref))
[1] 0
> ref <- ImmGenData()
> sce.ref <- as(ref, "SingleCellExperiment")
> max(normcounts(sce.ref))
[1] 14.9486
> min(normcounts(sce.ref))
[1] 2.3044
> ref <- MouseBulkData()
> sce.ref <- as(ref, "SingleCellExperiment")
> max(normcounts(sce.ref))
[1] 25.14407
> min(normcounts(sce.ref))
[1] 3.336021
> ref <- HumanPrimaryCellAtlasData()
> sce.ref <- as(ref, "SingleCellExperiment")
> max(normcounts(sce.ref))
[1] 15.1882
> min(normcounts(sce.ref))
[1] 2.7489
```

**Comment by friedue** [comment]
All reference data set values have been log-transformed, AFAIK (@dviraran please confirm).

`normcounts` is just the name we assigned, i.e. the containers returned by the data retrieval functions do not have any other assay slot filled.

`logexprs` may be a more fitting alternative since not all the values are count-derived (because they came from microarray results). But I don't think that's a standard `assay` name. Anyway, if we do want to rename them, now would be the time.

**Comment by bbimber** [comment]
OK.  Also - can you comment on label.main vs. label.fine?  At least with HCPA data, I understand the course vs. fine labels.  However, it there any way to obtain both labels with a single execution of SingleR()?  I thought the published version did that for us.  Or do we need to execute that method twice?

**Comment by j-andrews7** [comment]
You'll have to run it twice. However, even running it twice with the new version is quicker than a single run of the old version. By orders of magnitude if you have lots of cells. 

You can also get a slight speedup by forgoing the `SingleR()` wrapper and running `trainSingleR()` once on the reference set and then doing subsequent runs of `classifySingleR()` with different reference sets/labels/clusters.

**Comment by LTLA** [comment]
> You can also get a slight speedup by forgoing the `SingleR()` wrapper and running `trainSingleR()` once on the reference set and then doing subsequent runs of `classifySingleR()` with different reference sets/labels/clusters.

Slight correction - `trainSingleR()` requires the labels to be known. So if you have new labels, you'd need to rerun `trainSingleR()`. But that's still okay, you just have two trained objects instead of one.

**Comment by LTLA** [comment]
@friedue I think `"logcounts"` would be the most expedient approach, even if they aren't really counts.

**Comment by j-andrews7** [comment]
Oh woops, good catch. I agree with the `"logcounts"` approach.

**Comment by j-andrews7** [comment]
@bbimber, all of the reference datasets now use `"logcounts"` in the latest version, so you shouldn't have to use your correction above any longer.

**Comment by bbimber** [comment]
Thanks.  

And to confirm one other thing: in my post above, when taking counts from a seurat object, I wrote: sce <- scater:::logNormCounts(sce, log = T).  Is log=T desired here?

**Comment by j-andrews7** [comment]
You can leave it off if you want, it is `TRUE` by default.

**Comment by bbimber** [comment]
sorry, somehow completely missed that...

**Comment by LTLA** [comment]
I can't help but say this: `T` is evil. If you want to mess with other people using your R installation, you can try the relevant trick [here](https://purrple.cat/blog/2017/05/28/turn-r-users-insane-with-evil/). The thing is, it's not even that hard to do accidentally, one might naturally assign something to `T` (Brachyury) or to `F` (F-statistics) and break downstream code.

**Comment by LTLA** [comment]
Assuming that this was resolved.
