### ISSUE TITLE
mathematical principle,    thank you very much

### ISSUE THREAD

**Issue by zznx** [LTLA/SingleR#160]
Sorry to bother you, but I would like to ask what is the mathematical principle of the following code. Thank you very much.Can you elaborate on it? Thank you most sincerely

trainSingleR
```
.scaled_colranks_safe <- function(x) {
    out <- colRanks(DelayedArray(x), ties.method="average")
    center <- (nrow(x) + 1)/2
    sum.sq <- rowVars(out, center=center) * (nrow(x)-1)
    sum.sq <- pmax(1e-8, sum.sq)
    (out - center)/(sqrt(sum.sq) * 2)
}
```
@LTLA

**Comment by zznx** [comment]
![image](https://user-images.githubusercontent.com/38571101/99960015-0628a180-2dc7-11eb-9cc9-ffb63f7b21eb.png)
Is this how rowVars is implemented? Is center the square of the average
thank you very much

**Comment by LTLA** [comment]
What's to explain? You convert each cell's expression profile into ranks, then you center and scale those ranks. 

- The mean rank within each cell  is always `(nrow(x) +  1)/2`.
- `colRanks` returns its output in transposed form by default (cells are now rows), hence `rowVars()`.

Eucliean distances between scaled and centered rank vectors can then be easily transformed into Spearman correlations.

**Comment by zznx** [comment]
I looked at it, and this is amazing, an optimization of an algorithm that reduces the computation time.
I don't know why we dividing by SQRT (sum.sq) * 2 instead of rowVars(out, center=center)
I know I probably shouldn't ask, but I hope someone will help me. Thank you
`(x-u)/s`

**Comment by LTLA** [comment]
This is the scaling factor necessary to obtain a distance that can be directly converted to the Spearman correlation. You could of course just divide by the standard deviations, but then you would have to do the scaling downstream, so it is done here instead.

**Comment by zznx** [comment]
Thank you for your reply. Can you tell me what the compression ratio should be and how to determine it?

```
(x-u)/σ
sqrt(sum.sq)* 2=sqrt(s*(n-1))*2=σ*sqrt(n-1)*2
```

**Comment by zznx** [comment]
I'm not sure.Is that right?  Thank you in advance
1/(n-1)*sum(x-mean(x))^2 *(n-1)=sum(x-mean(x))^2
sqrt(sum(x-mean(x))^2)=sum(x-mean(x)) 
sum(x-mean(x))

**Comment by zznx** [comment]
I think I know. Buildindex has Euclidean and Manhattan distances, and the scaling factor can be converted into Spearman correlation. Is that right?
```
m1=(x-u)/∑(x-u)^2 *2
(∑(m1-km$centers))^(1/2)=spearman correlation
```
It would be nice to have a more detailed derivation

Thank you for the packages

**Comment by LTLA** [comment]
You can check out https://arxiv.org/abs/1208.3145 for more details.

**Comment by zznx** [comment]
Thank you for your reply.The following is my understanding.Is that right?
X and Y calculated the correlation coefficient through the sorted data, and the result was Spearman, which required two objects X and Y.Here, X is normalized and compressed, and y is the center of mass. Kmeans is optimized by triangular inequality

**Comment by LTLA** [comment]
Hard to say whether you're right or wrong here, I don't understand the meaning of any of your sentences.

> X and Y calculated the correlation coefficient through the sorted data, and the result was Spearman, which required two objects X and Y.

Um. I'll just say this:

```r
set.seed(0)
x <- runif(100)
y <- runif(100)
cor(x, y, method="spearman") # our reference value
## [1] 0.01018902

ranked.x <- scale(rank(x)) / sqrt(length(x) - 1) / 2
ranked.y <- scale(rank(y)) / sqrt(length(y) - 1) / 2
1 - 2 *sum((ranked.x - ranked.y)^2) # based on the Euclidean distance
## [1] 0.01018902
```

> Here, X is normalized and compressed, and y is the center of mass.

Don't know what you mean here.

> Kmeans is optimized by triangular inequality

I assume you're referring to the nearest neighbor search. The k-means clustering provides the indexing structure that enables a more efficient search, by using the triangular inequality to eliminate search paths that cannot give closer neighbors.

**Comment by zznx** [comment]
Hi

```
set.seed(0)
x <- runif(100)
y <- runif(100)
cor(x, y, method="pearson")
##0.01840209

## COSINE SIMILARITY
scale.x=scale(x)
scale.y=scale(y)
sum(scale.x * scale.y) / sqrt(sum(scale.x^2))/sqrt(sum(scale.y^2))
## 0.01840209

cos(m)=1-2*sin(m/2)**2

```
Is sin(m/2)^2 and sum((x - y)^2) equivalent ?

**Comment by zznx** [comment]
```
c1=c2=c(1,2,3,4,5,6,7)
cor(c1-4, c2-4, method="pearson")  #pearson
##0.9642857
cor(c1-4, c2-4, method="spearman") #spearman
##0.9642857
sum((c1-4)*(c2-4))/sqrt((sum((c1-4)^2)*sum((c2-4)^2))) #cosine similarity 
##0.9642857
Sun D, et al. (2011) Angular decomposition. In: Proceedings of the Twenty-Second International Joint Conference on Artificial Intelligence. IJCAI ’11, pp. 1505-1510.
```
I totally get it, and I came here to thank you for teaching me
