### ISSUE TITLE
per-cell vs per-cluster annotation

### ISSUE THREAD

**Issue by igordot** [LTLA/SingleR#165]
I hope this was not addressed somewhere previously, so apologies if it was. The main `SingleR()` function can perform annotation for cells or for clusters. If it's possible to annotate cells, why use clusters? Obviously cluster expression values will be less sparse, but then you have to decide on the "right" number of clusters. Is one method preferable over the other or is the option simply there because it's possible?

**Comment by LTLA** [comment]
Some comments at http://bioconductor.org/books/release/SingleRBook/advanced-options.html#cluster-level-annotation.

**tl;dr** it's quick and dirty.

**Comment by igordot** [comment]
Thank you! I was afraid it would be a much more nuanced answer.

**Comment by dviraran** [comment]
Another advantage of clusters is that you are seeing more non zero genes, which should improve the inference.

The main disadvantage is that clusters are many times not homogeneous enough (contain multiple cell types), which will just confuse SingleR. On the single-cell level you can identify non-homogeneous clusters.

One favorite methodology is to use clusters with very high resolution for SingleR. This gives the benefits from both worlds.
