### ISSUE TITLE
force to use cache data for HumanPrimaryCellAtlasData

### ISSUE THREAD

**Issue by billzt** [LTLA/SingleR#167]
Every day when I run
```
library(celldex)
ref.data <- HumanPrimaryCellAtlasData(ensembl=TRUE)
```

It began to download data to `.cache/ExperimentHub`. Since my network speed is very slow, is there any parameters to forbid it to download multiple times and only use the cache data?

**Comment by LTLA** [comment]
You should be able to force **ExperimentHub** to use the local cache only with:

```r
library(ExperimentHub)
setExperimentHubOption("LOCAL", TRUE)
```

Obviously, if this is turned on, you won't be able to download new datasets.

FYI the function is probably not downloading data. It's instead downloading the _manifest_ for ExperimentHub, i.e., a small SQLite file that describes the set of all available datasets. On my computer, it's about 5 MB... I suppose your connection must be pretty bad if this is taking a long time.
