### ISSUE TITLE
Error using SingleR - can't load celldex and can't use blueprint

### ISSUE THREAD

**Issue by EdoPredi** [LTLA/SingleR#168]
Hi. 

I am using mac versionVersion 1.3.1093 of R studio:

 Today I wanted to try to use singleR on my B cells dataset. So I checked online and I found this tutorial on bioconductor: 
https://bioconductor.org/books/release/OSCA/cell-type-annotation.html

I have tried to follow the instructions but I got several error:
**1) when Loading SingleR several objects are masked:**

**2) Error: I basically can't install celldex.**

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

The following initializes usage of Bioc devel
BiocManager::install(version='devel')

Error in library(celldex) : there is no package called ‘celldex’
> if (!requireNamespace("BiocManager", quietly = TRUE))
+   install.packages("BiocManager")
The following initializes usage of Bioc devel
> BiocManager::install(version='devel')
Error: Bioconductor version '3.13' requires R version '4.1'; see https://bioconductor.org/install
> 

BiocManager::install("celldex")

> BiocManager::install("celldex")
Bioconductor version 3.11 (BiocManager 1.30.10), R 4.0.1 (2020-06-06)
Installing package(s) 'celldex'
Warning message:
package ‘celldex’ is not available (for R version 4.0.1) 

**3) I have tried a workaround using :** 

 > ref <- BlueprintEncodeData()
/Users/eddy/Library/Caches/ExperimentHub
  does not exist, create directory? (yes/no): ref
/Users/eddy/Library/Caches/ExperimentHub
  does not exist, create directory? (yes/no): yes

**but when I run my cells I get this:**

> View(ref)
> SingleRCarejavi <- CarejaviSeuratF
> rm(SingleR)
> pred <- SingleR(test= SingleRCarejavi, ref=ref, labels=ref$label.main)
Warning: The following arguments are not used: drop
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'type': Cannot find cells provided

I am pretty sure I am doing something terribly wrong. Any chances anyone can help me?

**Comment by LTLA** [comment]
> **1) when Loading SingleR several objects are masked:**

The masking isn't a problem, the SingleR functions just call the celldex ones anyway (with a deprecation warning).

> > package ‘celldex’ is not available (for R version 4.0.1)

**celldex** is in BioC 3.12 or higher, so if you want it, you'll need to upgrade your version of Bioconductor:

```r
BiocManager::install(version="3.12")
```

> SingleRCarejavi <- CarejaviSeuratF

Looks like you're trying to use a Seurat object in there. As `?SingleR` describes, you'll either need a count matrix, a `SummarizedExperiment` object or any one of the SE subclasses (e.g., a `SingleCellExperiment`).

**Comment by j-andrews7** [comment]
Assuming this has been resolved, feel free to reopen if you're still having issues.
