### ISSUE TITLE
reason: database is locked

### ISSUE THREAD

**Issue by zhengxinchang** [LTLA/SingleR#169]
Hi dear developers，

I'm getting into trouble when I ran the latest version of SingleR and celldex

I ran commands as below:

```
library(Seurat)
library(tidyverse)
library(SingleR)
library(ExperimentHub)
setExperimentHubOption("LOCAL", TRUE)
blood.se<-celldex::NovershternHematopoieticData(ensembl=TRUE)

```

and I got the error messages:
```
snapshotDate(): 2020-12-22
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
snapshotDate(): 2020-10-27
loading from cache
require(“ensembldb”)
Error: failed to load resource
  name: AH73881
  title: Ensembl 97 EnsDb for Homo sapiens
  reason: database is locked
In addition: Warning message:
Couldn't set synchronous mode: database is locked
Use `synchronous` = NULL to turn off this warning.
```

I am sure that there is no other R session using the database at the same time. 

could you please help me handle this issue?

**Comment by LTLA** [comment]
You don't show your session information, so I'll just have to assume your installation is up to date.

Anyway, I can't reproduce your error. Running the below:

```r
blood.se<-celldex::NovershternHematopoieticData(ensembl=TRUE)
```

Gives me:

```
snapshotDate(): 2020-12-22
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
see ?celldex and browseVignettes('celldex') for documentation
loading from cache
  |======================================================================| 100%

snapshotDate(): 2020-10-27
downloading 1 resources
retrieving 1 resource
  |======================================================================| 100%

loading from cache
require(“ensembldb”)
Warning message:
Unable to map 3426 of 13276 requested IDs. 
```

I've never seen a "database is locked" error before, so I don't really know what's going on. 

Best guess is that you were running an R session that was holding the lock on this file, and then the R session crashed without the opportunity to release the lock (e.g., if your computer ran out of memory or there was a segmentation fault). The OS would normally release the locks for you but maybe something went wrong. Indeed, forcibly killing R in the middle of a download gives me:

```
Error: failed to load resource
  name: AH73881
  title: Ensembl 97 EnsDb for Homo sapiens
  reason: database disk image is malformed
In addition: Warning message:
Couldn't set synchronous mode: database disk image is malformed
Use `synchronous` = NULL to turn off this warning. 
```

which is not quite the same error but it might be in the same category. 

You might try deleting the cache directory at:

```r
library(AnnotationHub)
hubCache(AnnotationHub())
## [1] "/home/luna/.cache/AnnotationHub"
```

and start fresh. That got me back on track after the "malformed" error above.
