### ISSUE TITLE
issues about install

### ISSUE THREAD

**Issue by amjiuzi** [LTLA/SingleR#17]
`devtools::install_github('LTLA/SingleR')`

@LTLA 

Downloading GitHub repo LTLA/SingleR@master
Installing 8 packages: DelayedMatrixStats, BiocNeighbors, BiocFileCache, ExperimentHub, beachmat, HDF5Array, Rhdf5lib, rhdf5

package ‘DelayedMatrixStats’ successfully unpacked and MD5 sums checked
package ‘BiocNeighbors’ successfully unpacked and MD5 sums checked
package ‘BiocFileCache’ successfully unpacked and MD5 sums checked
package ‘ExperimentHub’ successfully unpacked and MD5 sums checked
package ‘beachmat’ successfully unpacked and MD5 sums checked
package ‘HDF5Array’ successfully unpacked and MD5 sums checked
package ‘Rhdf5lib’ successfully unpacked and MD5 sums checked
package ‘rhdf5’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\zhegu\AppData\Local\Temp\RtmpCqDKu6\downloaded_packages
√  checking for file 'C:\Users\zhegu\AppData\Local\Temp\RtmpCqDKu6\remotes19d058b1584d\LTLA-SingleR-a2a8921/DESCRIPTION' (988ms)
-  preparing 'SingleR': (363ms)
√  checking DESCRIPTION meta-information ...
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (398ms)
-  checking for empty or unneeded directories
-  building 'SingleR_0.99.4.tar.gz'
   
* installing *source* package 'SingleR' ...
** libs
C:/RBUILD~1/3.4/mingw_64/bin/g++  -std=gnu++11 -I"D:/R/soft/R-35~1.3/include" -DNDEBUG  -I"D:/R/soft/R-3.5.3/library/Rcpp/include" -I"D:/R/soft/R-3.5.3/library/beachmat/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBUILD~1/3.4/mingw_64/bin/g++  -std=gnu++11 -I"D:/R/soft/R-35~1.3/include" -DNDEBUG  -I"D:/R/soft/R-3.5.3/library/Rcpp/include" -I"D:/R/soft/R-3.5.3/library/beachmat/include"        -O2 -Wall  -mtune=generic -c fine_tune_de.cpp -o fine_tune_de.o
In file included from D:/R/soft/R-3.5.3/library/beachmat/include/beachmat/all_readers.h:4:0,
                 from D:/R/soft/R-3.5.3/library/beachmat/include/beachmat/LIN_matrix.h:4,
                 from D:/R/soft/R-3.5.3/library/beachmat/include/beachmat/numeric_matrix.h:4,
                 from fine_tune_de.cpp:1:
D:/R/soft/R-3.5.3/library/beachmat/include/beachmat/beachmat.h:15:19: fatal error: H5Cpp.h: No such file or directory
 #include "H5Cpp.h"
                   ^
compilation terminated.
make: *** [fine_tune_de.o] Error 1
ERROR: compilation failed for package 'SingleR'
* removing 'D:/R/soft/R-3.5.3/library/SingleR'
In R CMD INSTALL
Error: Failed to install 'SingleR' from GitHub:
  (converted from warning) installation of package ‘C:/Users/zhegu/AppData/Local/Temp/RtmpCqDKu6/file19d06502ecf/SingleR_0.99.4.tar.gz’ had non-zero exit status

**Comment by j-andrews7** [comment]
You need R >= 3.6 and to ensure dependencies are installed from Bioc devel.

**Comment by LTLA** [comment]
Assuming that this was resolved.
