### ISSUE TITLE
can i annotate cells in specific cell types?

### ISSUE THREAD

**Issue by hansonglee** [LTLA/SingleR#172]
Hi, I'm using SingleR for annotating my pbmc data.

I have annotated cells (CD4T cell, CD8T cell, B cell, monocyte and so on) and
now, i want to assign annotated CD4T cells into more detailed subtypes like Th1, Th2, T reg..

Is there any way to specify main cell types (CD4T) to assign related fine clusters (Th1, Th2, T reg..)?

**Comment by j-andrews7** [comment]
Sure, just split your input matrix (or SCE) by your initial annotations and run SingleR on each main cell type individually. You might consider splitting the reference dataset to use only the subtypes of interest as well (e.g. only use the T cell subtypes).
