### ISSUE TITLE
Cannot get SingleR to load

### ISSUE THREAD

**Issue by jcook-ucsf** [LTLA/SingleR#173]
Hello- I'm having major problems downloading the appropriate packages onto my laptop. I just did this on my desktop with no issue, so I'm not sure what's happening 

I'm installing Bioconductor as per the website's directions, I get all this "Cannot Open URL" warning messages. From searching around, it seems this is a result of having incompatible versions of Bioconductor and R, but I'm running R 4.03, I'll paste my session info below. It seems like BiocManager is installed, but when I go to install SingleR, I get the same "cannot open URL" warning and the packages won't download. Any tips on this?

> if (!requireNamespace("BiocManager", quietly = TRUE))
+     install.packages("BiocManager")
> BiocManager::install(version = "3.12")
Bioconductor version 3.12 (BiocManager 1.30.10), R 4.0.3 (2020-10-10)
Old packages: 'DBI', 'dplyr', 'edgeR', 'fansi', 'Rcpp', 'tibble'
Update all/some/none? [a/s/n]: 
a
cannot open URL 'https://bioconductor.org/packages/3.12/data/annotation/bin/macosx/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.12/data/annotation/bin/macosx/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.12/data/experiment/bin/macosx/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.12/data/experiment/bin/macosx/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.12/workflows/bin/macosx/contrib/4.0/PACKAGES.rds': HTTP status was '404 Not Found'cannot open URL 'https://bioconductor.org/packages/3.12/workflows/bin/macosx/contrib/4.0/PACKAGES.gz': HTTP status was '404 Not Found'
  There are binary versions available but the source versions are later:

Do you want to install from sources the packages which need compilation? (Yes/no/cancel) yes
trying URL 'https://bioconductor.org/packages/3.12/bioc/bin/macosx/contrib/4.0/edgeR_3.32.1.tgz'
Content type 'application/x-gzip' length 2450719 bytes (2.3 MB)
==================================================
downloaded 2.3 MB

The downloaded binary packages are in
	/var/folders/lc/rl4j0x_55bl9jgqpcbbz9m840000gn/T//RtmpakFdY2/downloaded_packages
installing the source packages 'DBI', 'dplyr', 'fansi', 'Rcpp', 'tibble'

trying URL 'https://cran.rstudio.com/src/contrib/DBI_1.1.1.tar.gz'
Content type 'application/x-gzip' length 743802 bytes (726 KB)
==================================================
downloaded 726 KB

trying URL 'https://cran.rstudio.com/src/contrib/dplyr_1.0.3.tar.gz'
Content type 'application/x-gzip' length 946024 bytes (923 KB)
==================================================
downloaded 923 KB

trying URL 'https://cran.rstudio.com/src/contrib/fansi_0.4.2.tar.gz'
Content type 'application/x-gzip' length 271435 bytes (265 KB)
==================================================
downloaded 265 KB

trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_1.0.6.tar.gz'
Content type 'application/x-gzip' length 2952876 bytes (2.8 MB)
==================================================
downloaded 2.8 MB

trying URL 'https://cran.rstudio.com/src/contrib/tibble_3.0.5.tar.gz'
Content type 'application/x-gzip' length 548456 bytes (535 KB)
==================================================
downloaded 535 KB

* installing *source* package ‘DBI’ ...
** package ‘DBI’ successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (DBI)
* installing *source* package ‘fansi’ ...
** package ‘fansi’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c assumptions.c -o assumptions.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c has.c -o has.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c nchar.c -o nchar.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c read.c -o read.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c rnchar.c -o rnchar.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c state.c -o state.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c strip.c -o strip.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c strsplit.c -o strsplit.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c tabs.c -o tabs.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c tohtml.c -o tohtml.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c unhandled.c -o unhandled.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c unique.c -o unique.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c utf8.c -o utf8.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c utils.c -o utils.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c wrap.c -o wrap.o
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o fansi.so assumptions.o has.o init.o nchar.o read.o rnchar.o state.o strip.o strsplit.o tabs.o tohtml.o unhandled.o unique.o utf8.o utils.o wrap.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-fansi/00new/fansi/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (fansi)
* installing *source* package ‘Rcpp’ ...
** package ‘Rcpp’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c api.cpp -o api.o
In file included from api.cpp:24:
In file included from ../inst/include/Rcpp.h:57:
../inst/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c attributes.cpp -o attributes.o
In file included from attributes.cpp:39:
In file included from ../inst/include/Rcpp.h:57:
../inst/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c barrier.cpp -o barrier.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c date.cpp -o date.o
In file included from date.cpp:30:
In file included from ../inst/include/Rcpp.h:57:
../inst/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c module.cpp -o module.o
In file included from module.cpp:24:
In file included from ../inst/include/Rcpp.h:57:
../inst/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG -I../inst/include/  -I/usr/local/include   -fPIC  -Wall -g -O2  -c rcpp_init.cpp -o rcpp_init.o
In file included from rcpp_init.cpp:24:
In file included from ../inst/include/Rcpp.h:57:
../inst/include/Rcpp/DataFrame.h:136:18: warning: unused variable 'data' [-Wunused-variable]
            SEXP data = Parent::get__();
                 ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o Rcpp.so api.o attributes.o barrier.o date.o module.o rcpp_init.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-Rcpp/00new/Rcpp/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (Rcpp)
* installing *source* package ‘tibble’ ...
** package ‘tibble’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c attributes.c -o attributes.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c coerce.c -o coerce.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.c -o init.o
clang -mmacosx-version-min=10.13 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c matrixToDataFrame.c -o matrixToDataFrame.o
clang -mmacosx-version-min=10.13 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o tibble.so attributes.o coerce.o init.o matrixToDataFrame.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-tibble/00new/tibble/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (tibble)
* installing *source* package ‘dplyr’ ...
** package ‘dplyr’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c chop.cpp -o chop.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c filter.cpp -o filter.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c funs.cpp -o funs.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c group_by.cpp -o group_by.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c group_data.cpp -o group_data.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c imports.cpp -o imports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c init.cpp -o init.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c mask.cpp -o mask.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c mutate.cpp -o mutate.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c slice.cpp -o slice.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c summarise.cpp -o summarise.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o dplyr.so chop.o filter.o funs.o group_by.o group_data.o imports.o init.o mask.o mutate.o slice.o summarise.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-dplyr/00new/dplyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
*** copying figures
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (dplyr)

The downloaded source packages are in
	'/private/var/folders/lc/rl4j0x_55bl9jgqpcbbz9m840000gn/T/RtmpakFdY2/downloaded_packages'
> library(BiocManager)
Bioconductor version 3.12 (BiocManager 1.30.10), ?BiocManager::install for help
**session info**
> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scran_1.18.3                scRNAseq_2.4.0              SingleCellExperiment_1.12.0
 [4] SingleR_1.4.0               celldex_1.0.0               SummarizedExperiment_1.20.0
 [7] Biobase_2.50.0              GenomicRanges_1.42.0        GenomeInfoDb_1.26.2        
[10] IRanges_2.24.1              S4Vectors_0.28.1            BiocGenerics_0.36.0        
[13] MatrixGenerics_1.2.0        matrixStats_0.57.0          BiocManager_1.30.10        

loaded via a namespace (and not attached):
 [1] ProtGenerics_1.22.0           bitops_1.0-6                  bit64_4.0.5                  
 [4] progress_1.2.2                httr_1.4.2                    tools_4.0.3                  
 [7] R6_2.5.0                      irlba_2.3.3                   lazyeval_0.2.2               
[10] DBI_1.1.1                     withr_2.3.0                   tidyselect_1.1.0             
[13] prettyunits_1.1.1             bit_4.0.4                     curl_4.3                     
[16] compiler_4.0.3                cli_2.2.0                     BiocNeighbors_1.8.2          
[19] xml2_1.3.2                    DelayedArray_0.16.0           rtracklayer_1.50.0           
[22] askpass_1.1                   rappdirs_0.3.1                stringr_1.4.0                
[25] digest_0.6.27                 Rsamtools_2.6.0               XVector_0.30.0               
[28] pkgconfig_2.0.3               htmltools_0.5.1               sparseMatrixStats_1.2.0      
[31] limma_3.46.0                  ensembldb_2.14.0              dbplyr_2.0.0                 
[34] fastmap_1.0.1                 htmlwidgets_1.5.3             rlang_0.4.10                 
[37] rstudioapi_0.13               RSQLite_2.2.2                 shiny_1.5.0                  
[40] DelayedMatrixStats_1.12.2     generics_0.1.0                BiocParallel_1.24.1          
[43] dplyr_1.0.3                   RCurl_1.98-1.2                magrittr_2.0.1               
[46] BiocSingular_1.6.0            scuttle_1.0.4                 GenomeInfoDbData_1.2.4       
[49] Matrix_1.3-2                  Rcpp_1.0.6                    fansi_0.4.2                  
[52] lifecycle_0.2.0               edgeR_3.32.1                  stringi_1.5.3                
[55] yaml_2.2.1                    zlibbioc_1.36.0               BiocFileCache_1.14.0         
[58] AnnotationHub_2.22.0          grid_4.0.3                    blob_1.2.1                   
[61] dqrng_0.2.1                   promises_1.1.1                ExperimentHub_1.16.0         
[64] crayon_1.3.4                  lattice_0.20-41               Biostrings_2.58.0            
[67] beachmat_2.6.4                GenomicFeatures_1.42.1        hms_1.0.0                    
[70] locfit_1.5-9.4                knitr_1.30                    pillar_1.4.7                 
[73] igraph_1.2.6                  biomaRt_2.46.0                XML_3.99-0.5                 
[76] glue_1.4.2                    BiocVersion_3.12.0            data.table_1.13.6            
[79] vctrs_0.3.6                   httpuv_1.5.5                  openssl_1.4.3                
[82] purrr_0.3.4                   assertthat_0.2.1              xfun_0.20                    
[85] rsvd_1.0.3                    mime_0.9                      xtable_1.8-4                 
[88] AnnotationFilter_1.14.0       later_1.1.0.1                 tibble_3.0.5                 
[91] GenomicAlignments_1.26.0      AnnotationDbi_1.52.0          memoise_1.1.0                
[94] statmod_1.4.35                bluster_1.0.0                 ellipsis_0.3.1               
[97] interactiveDisplayBase_1.28.0

**Comment by dtm2451** [comment]
Hi @jcook-ucsf,

It looks to me like the messages you are getting are not actually preventing installation. These trying URL messages pop up often when particular package mirrors have issues or are unreachable during installation, but it seems that a viable source was eventually found; from your session info, we can see that you do now have the current version of SingleR & celldex installed! `[4] SingleR_1.4.0 celldex_1.0.0`.

-Dan, a fellow UCSFer =)

PS for better formatting of code / output in future, wrap it inside of:

\`\`\`
code
\`\`\`

**Comment by jcook-ucsf** [comment]
Hi Dan, oh, great, I'll try running it again then. Thanks for the tip on formatting code :)
