### ISSUE TITLE
Using a scalar value for argument 'center' is now deprecated.

### ISSUE THREAD

**Issue by ycl6** [LTLA/SingleR#177]
I recently upgraded `matrixStats` from CRAN and now I am getting below messages when running `SingleR`

```
Warning message:
"Argument 'center' should be of the same length as number of rows of 'x'. Use of a scalar value is deprecated: 1 != 9"
Warning message:
"Argument 'center' should be of the same length as number of rows of 'x'. Use of a scalar value is deprecated: 1 != 2"
Warning message:
"Argument 'center' should be of the same length as number of rows of 'x'. Use of a scalar value is deprecated: 1 != 8"
Warning message:
"Argument 'center' should be of the same length as number of rows of 'x'. Use of a scalar value is deprecated: 1 != 14"
Warning message:
"Argument 'center' should be of the same length as number of rows of 'x'. Use of a scalar value is deprecated: 1 != 5"
```

It appears from v0.58.0 `matrixStats` is no longer accepting scalar value for argument 'center', in this case, in `rowVars`

https://github.com/LTLA/SingleR/blob/db2a5415501e345a8f4dba02c86a2495f19460e7/R/trainSingleR.R#L431-L435

https://github.com/HenrikBengtsson/matrixStats/blob/master/NEWS

https://github.com/HenrikBengtsson/matrixStats/issues/193

**Comment by LTLA** [comment]
Yes, I'm aware of those discussions. I may have inadvertently set the whole thing off with PeteHaitch/DelayedMatrixStats#64.

You can ignore these warnings, a fix is in 17f5fbd72f9bb2ada005e18446f704371b3b72fc.
