### ISSUE TITLE
Is it acceptable to classify 10x data using samrtseq data as reference?

### ISSUE THREAD

**Issue by smk5g5** [LTLA/SingleR#178]
Considering that the distribution of gene counts of Smartseq data is considerably different from 10x data is it an acceptable strategy to classify 10x data using public smartseq2 datasets?

The smartseq data that I have is available publicly as TPMs I can log normalize it ln(x+1) and store it as a single cell experiment object and use the annotated celltypes along with TPM data to make predictions using SingleR. Would this be an acceptable strategy or is there a better way to do it to get more robust celltype predictions?

Thanks!

**Comment by dviraran** [comment]
Shouldn’t be a problem. We used references from many different types (bulk RNA-seq, microarrays, CAGE, etc.) and all work well. SingleR uses Spearman correlations, so only the rank matters, normalizations and log scale have marginal effect.
