### ISSUE TITLE
Error in `[<-`(`*tmp*`, , u, value = rowMedians(DelayedArray(mat), cols = u ==  :    subscript out of bounds

### ISSUE THREAD

**Issue by xujingmei111** [LTLA/SingleR#182]
command:
pred <- SingleR(test=test_data, ref=refdata, labels=as.character(main_label))

then get the error:
Error in `[<-`(`*tmp*`, , u, value = rowMedians(DelayedArray(mat), cols = u ==  : 
  subscript out of bounds

when:
pred <- SingleR(test=test_data, ref=refdata, labels=as.character(main_label),de.method="wilcox")
Error in all.n[[b]][[target]] : subscript out of bounds

What's the problem?How can I fix it ?

**Comment by LTLA** [comment]
¯\\\_(ツ)\_/¯

Can you make a [minimal reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)? Can you show your session information?

If you can't, I can only supply guesses. Check that `test_data` is a matrix, sparse matrix, or `DelayedMatrix`. Same for `refdata`. make sure that `main_label` doesn't have any weird stuff in it, e.g., no `NA`s or weird unicode characters.

**Comment by xujingmei111** [comment]
> ¯\_(ツ)_/¯
> 
> Can you make a [minimal reproducible example](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)? Can you show your session information?
> 
> If you can't, I can only supply guesses. Check that `test_data` is a matrix, sparse matrix, or `DelayedMatrix`. Same for `refdata`. make sure that `main_label` doesn't have any weird stuff in it, e.g., no `NA`s or weird unicode characters.

Yes,you're right! You made my day! The main_lable contains Null and "II" which were neglected before , it worked after I have fixed it ! Thanks so much!
