### ISSUE TITLE
How to use SingleR for integration analysis in Seurat?

### ISSUE THREAD

**Issue by lkqnaruto** [LTLA/SingleR#185]
Hi

I'm currently working on the cell type annotation task using Seurat, where I have 3 samples for control group, 8 samples for treatment group, and I would like to know the cell type for each group. Then I integrated the samples within each group.

I have a question regarding to SingleR:
After I got integrated data, should I pass the integrated assay data to SingleR? or the RNA assay data to SingleR? 

During the diagnostic step, would it be always better to use prune label column? rather than label column.

Thanks

**Comment by LTLA** [comment]
Pass the raw counts, see the discussion in #98.

The `prune.label` column is just a more conservative version of `label`. It assumes that, for the set of cells assigned to a given label, the majority of them are correctly assigned, and it will trim away the calls with relatively poor scores. It won't provide much protection against major errors, e.g., when the true cell type is not in the reference so **SingleR** assigns it to the closest matching type.

**Comment by lkqnaruto** [comment]
Thank you for the response. The discussion in #98 is great to learn. 

Just want to double check, the raw counts is located at the integrated Seurat object, RNA assay, slot counts, right?

**Comment by j-andrews7** [comment]
Yes, that's correct as far as I remember.

**Comment by lkqnaruto** [comment]
@j-andrews7 Thank you for the reply
