### ISSUE TITLE
get colors used in heatmap

### ISSUE THREAD

**Issue by pcantalupo** [LTLA/SingleR#187]
Hello, is there a way to determine the color hex codes used for each "Labels" in the plotScoreHeatmap function? I'd like to use the same colors for other plots like scater::plotUMAP, etc....

Thank you

**Comment by dtm2451** [comment]
Hey there!  The colors used currently are pulling from https://github.com/LTLA/SingleR/blob/ec13b5d564b7584582201d52eeade43445464761/R/plotScoreHeatmap.R#L531-L546.

Ultimately, this is copied over from `dittoSeq::dittoColors()` which I maintain.  If you have that package, then you can just use `dittoSeq::dittoColors(1)[1:24]` to arrive at a similar list.

Full truth though, I've updated the colors in dittoSeq a bit so this serves as a good reminder... @LTLA perhaps after Thursday, can I update the colors from the current 24 discrete options to the full 40 that are now in `dittoColors()`?

**Comment by LTLA** [comment]
I guess you could do it now if you want.

Kind of reminds me that we need a **BiocColors** package to host various palettes that can be shared, e.g., with **scater**.

**Comment by dtm2451** [comment]
That would be nice! I could certainly add to something like that if it were started, but I don't have the bandwidth to create the infrastructure from scratch.

**Comment by LTLA** [comment]
Probably @alanocallaghan might be interested. Could also see if you can rustle up some enthusiasm on the BioC slack.

**Comment by Alanocallaghan** [comment]
I have no idea what BiocColors is meant to be but I'd be quite happy to make a BiocColours package

**Comment by Alanocallaghan** [comment]
It's late; I will think about what else could be added tomorrow https://github.com/Alanocallaghan/BiocColors

**Comment by dtm2451** [comment]
Oh wow, I don't even have to add anything myself! =p

**Comment by dtm2451** [comment]
Sorry @pcantalupo for kinda hi-jacking the issue lol but feel free to close if my initial comment does cover things for you... We don't need this issue open as a reminder for the other bits that we ended up discussing as we already got all of them moving along =)

**Comment by pcantalupo** [comment]
@dtm2451 Thank you for your help. I think that solves my issue!
