### ISSUE TITLE
SingleR on Tabula Muris Seurat object fails Error in h(simpleError(msg, call))

### ISSUE THREAD

**Issue by asmariyaz23** [LTLA/SingleR#193]
Hello,

I want to use [Tabula Muris's kidney dataset](https://figshare.com/articles/dataset/Robject_files_for_tissues_processed_by_Seurat/5821263) as reference to annotate my dataset. I used the following commands:

```
kidney <- load("~/Downloads/facs_Kidney_seurat_tiss.Robj",verbose=TRUE)
tiss <- UpdateSeuratObject(tiss)
pred.tm.SingleR <- SingleR(mouse.normalized_sce,tiss,tiss$annotation)
```

This is the error I get:
```
Warning: The following arguments are not used: drop
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'type': unused argument (drop = FALSE)
```

Could you help me figure out what I am doing wrong?

Thank you,
Asma

**Comment by j-andrews7** [comment]
You can't use a Seurat object directly as a reference, you must pull out the counts as a matrix or convert it to a SingleCellExperiment first.
