### ISSUE TITLE
Will the annotation result be different after some cells have been filtered out?

### ISSUE THREAD

**Issue by lkqnaruto** [LTLA/SingleR#194]
I wonder whether the annotation result will be any different after I delete some cells. For example, originally I have 100k cells after QC, then I "LogNormalize" my data and use SingleR to assign cell labels based on a reference set. Then I use a subset of my original dataset, let's say 80k cells in total. Is it possible that a cell was assigned to cell type A at first, but then be assigned to cell type B ? In both case, reference set stays the same.

**Comment by j-andrews7** [comment]
Nope, shouldn't matter on a cell by cell basis. Each cell is considered and
scored individually.
