### ISSUE TITLE
create custom reference dataset

### ISSUE THREAD

**Issue by andynkili** [LTLA/SingleR#200]
I am trying to infer correctly cell type using SingleR.
I have successfully annotated my Seurat clusters with the HPCA built-in reference (using this [link](https://bioconductor.org/books/release/OSCA/cell-type-annotation.html#assigning-cell-labels-from-reference-data) but the results seemed a bit inaccurate.
Now I would like to use custom references. However I cannot find the proper tutorial.
In this [link](https://bioconductor.org/books/release/OSCA/cell-type-annotation.html#using-custom-references), there is a chapter about custom references but I cannot find how the latter is built.
I have browsed the SingleR issues (closed and open) related to this topic but only found [broken url](https://comphealth.ucsf.edu/SingleR/SingleR_create.html). The closest topic was this [one](https://github.com/dviraran/SingleR/issues/136), but it was not clear.
Also I have looked into the [SingleR book ](http://bioconductor.org/books/release/SingleRBook/)without finding how to create a reference.
Should I start by creating a SingleR object (as described [here](https://rdrr.io/github/dviraran/SingleR/man/CreateBigSingleRObject.html)) but then how can I use it to infer cell types?
May you point at the right direction/page?

**Comment by LTLA** [comment]
Did you read Chapter 3 of the book?

**Comment by andynkili** [comment]
Thank you.
I found it in the sub-chapter 'Defining custom markers'.
