### ISSUE TITLE
Requesting training data

### ISSUE THREAD

**Issue by sagnikbanerjee15** [LTLA/SingleR#205]
I was wondering if you could please send me the data you used for training SingleR. Ideally, a file with rows and cols would be nice but I work off a seurat or anndata object. You can email it to sagnik.banenerjee@bms.com

Thank you.

**Comment by friedue** [comment]
The "in-built" reference data sets that will work out-of-the-box with SingleR can be found in the [celldex](https://bioconductor.org/packages/release/data/experiment/html/celldex.html) package.

**Comment by sagnikbanerjee15** [comment]
Thank you
