### ISSUE TITLE
Tissue source of different reference data for single cell annotation

### ISSUE THREAD

**Issue by amanzju** [LTLA/SingleR#206]
Hi,

I'm trying to figure out the right reference data to annotate my own single-cell RNA-seq test data. Say, I have a test data of blood (PBMC) tissue from the human, and in this regard, if I'm not wrong, I can use the MonacoImmuneData reference dataset (since the corresponding GSE144434 dataset clearly mentioned that the PBMCs were isolate from human). For other reference datasets, I can't figure out tissue sources.
Could you kindly explain to me how can I consider other reference datasets to annotate my own blood tissue sample dataset?

Thank you!
Aman

**Comment by j-andrews7** [comment]
See the [celldex vignette](http://bioconductor.org/packages/release/data/experiment/vignettes/celldex/inst/doc/userguide.html) for more information. Or check the documentation pages for each reference set, e.g. `?MonacoImmuneData`.
