### ISSUE TITLE
SingleR custom reference dataset making

### ISSUE THREAD

**Issue by Lumskie** [LTLA/SingleR#208]
I have been trying to make a custom reference dateset from  bulk RNA data.I couldn't make labels  in the summarizedexperiment object during conversion.How can I use this dataset without labels??

**Comment by dtm2451** [comment]
Labels are absolutely required, as otherwise SingleR will not know the cell types of your reference samples.  But it sounds like there may be just a bit of confusion at fault instead of any bug in the process!

Labels are read in through the `labels` input of `SingleR()`.  `labels` just needs to be a string vector of the same length as you have samples in ref (= `ncol(ref)`).  You can provide this vector of cell type labels directly.  And in fact, doing so has the same effect as the `SingleR(..., labels = <ref$labels_column_name>)` equivalent, which just pulls that vector out of `ref`.

**Comment by Lumskie** [comment]
> Labels are absolutely required, as otherwise SingleR will not know the cell types of your reference samples. But it sounds like there may be just a bit of confusion at fault instead of any bug in the process!
> 
> Labels are read in through the `labels` input of `SingleR()`. `labels` just needs to be a string vector of the same length as you have samples in ref (= `ncol(ref)`). You can provide this vector of cell type labels directly. And in fact, doing so has the same effect as the `SingleR(..., labels = <ref$labels_column_name>)` equivalent, which just pulls that vector out of `ref`.

Hi,

Thank you for your response!

I tried the way you suggested but all the predictions are coming out to be <integers>.Can you please give me the code which is used to create summarized experiment data from a bulk RNA seq count matrix?

**Comment by dtm2451** [comment]
You actually don't need to provide you ref data as a SummarizedExperiment.  As mentioned in the docs, you can give a counts matrix directly.

Can you provide the code that you used to run SingleR itself?  I can't what's going wrong without that as these objects seem like they should work for `ref` and `test`, assuming you give a valid string vector to `labels`.

Based on the reference data summary, it seems you could use the code below to generate such a `labels` vector, but again, please share your code.

Potential method of making `labels`, by removing rep#s, based on what I see above:
```
library(stringr)
labels <- str_remove(
    colnames(<ref>),
    "_[[:alpha:][:digit:]]*$"
)
```

**Comment by Lumskie** [comment]
> You actually don't need to provide you ref data as a SummarizedExperiment. As mentioned in the docs, you can give a counts matrix directly.
> 
> Can you provide the code that you used to run SingleR itself? I can't what's going wrong without that as these objects seem like they should work for `ref` and `test`, assuming you give a valid string vector to `labels`.
> 
> Based on the reference data summary, it seems you could use the code below to generate such a `labels` vector, but again, please share your code.
> 
> Potential method of making `labels`, by removing rep#s, based on what I see above:
> 
> ```
> library(stringr)
> labels <- str_remove(
>     colnames(<ref>),
>     "_[[:alpha:][:digit:]]*$"
> )
> ```

Hi,

I have resolved the issue.I was not supplying proper metadata which made this confusion.

On a completely different note,SingleR is trying to annotate all cells supplied in a dataset.For example in a brain sample which contains neurons,glia as well as Neuroblast when I supplied ref data which only contain Neuroblast data ,it is trying to label every cells as Neuroblast even though it clearly contains neurons.How to fine tune the result such that it only labels the corresponding cells having highest correlation and others are just chucked?

Thank you so much!!

**Comment by j-andrews7** [comment]
See `?pruneScores` and decrease the `nmads` parameter if necessary. Note that the approach used assumes that most cells are correctly assigned, so this may take some experimenting to get a good balance between pruning the labels for non-neuroblast cells and pruning labels from actual neuroblasts.

**Comment by Lumskie** [comment]
> See `?pruneScores` and decrease the `nmads` parameter if necessary. Note that the approach used assumes that most cells are correctly assigned, so this may take some experimenting to get a good balance between pruning the labels for non-neuroblast cells and pruning labels from actual neuroblasts.

Got it!!
Thank you so much!!
