### ISSUE TITLE
Modifications of DatabaseImmuneCellExpressionData() for epithelial cells?

### ISSUE THREAD

**Issue by blusoldier001** [LTLA/SingleR#212]
Hi,

I'm attempting to use some code that was written for single cell sequencing by someone else, however, I realized that it was written only for immune cells, not epithelial cells. Mainly, it uses DatabaseImmuneCellExpressionData() to create a database of cell types. Is there any way I could modify this for epithelial cells?

Thanks!

**Comment by j-andrews7** [comment]
Take a look through other options in [celldex](http://bioconductor.org/packages/release/data/experiment/vignettes/celldex/inst/doc/userguide.html). Or provide your own reference with the appropriate cell types included.
