### ISSUE TITLE
Not all clusters were annotated when "per-cluster" method was used

### ISSUE THREAD

**Issue by Evenlyeven** [LTLA/SingleR#213]
Thanks for developing this wonderful tool for scRNASeq!

I've been using "per-cell" method to annotate my data, it worked very well. Recently, I started to use "per-cluster" method to annotate my data with Seurat clusters. However, not all the clusters were annotated. In this case, 6 out of 18 clusters were annotated. I tried another reference, but same thing happened, only partial clusters were annotated. I wonder if there's anything I can optimize to make the "per-cluster" method to annotate all the clusters. 

Thank you very much in advance!

Code used:
library(SingleR)
ref <- ref_bladder@assays$SCT@data
ref.label <- ref_bladder$label
CAF.sc <- SingleR(test = GetAssayData(combined.pca.n.c.umap, assay = "SCT", slot = "data"),
                  ref = ref,
                  labels = ref.label,
                  clusters = combined.pca.n.c.umap$seurat_clusters,
                  de.method = "wilcox")
table(CAF.sc$labels)

Results:
> table(CAF.sc$labels)

  Dendritic cells Endothelial cells  Epithelial cells       Fibroblasts            Neuron           T cells 
                1                 1                 5                 7                 1                 2

**Comment by LTLA** [comment]
Your output looks fine to me. Consider providing a minimum reproducible example.

**Comment by Evenlyeven** [comment]
Just noticed that I misinterpreted the results, apologize!

**Comment by dtm2451** [comment]
One extra note though: As noted in other issues, using the SCTranformed assay is not recommended.  You might get better results with the "RNA" assay.
