### ISSUE TITLE
Generate mock data with correct number of genes

### ISSUE THREAD

**Issue by ycl6** [LTLA/SingleR#216]
In L48 of the `.mockRefData` function I reference below:

https://github.com/LTLA/SingleR/blob/d06e65f7b03ef61b7c7b1a670e718ea7900d21ca/R/mockData.R#L48

The default `ngenes` value is hardcoded, hence it won't generate the correct number of genes if `ngenes` is changed.

```R
mat <- matrix(rpois(ngenes*length(g), lambda=10*2^means[,g]), ncol=length(g))
```

**Comment by LTLA** [comment]
Thanks for spotting this; should be fixed on the latest `master` and in BioC-devel soon.
