### ISSUE TITLE
SingleR Issue. 

### ISSUE THREAD

**Issue by sivaraja23** [LTLA/SingleR#218]
Hello! 
I am annotating my clusters using SingleR by this following code:
SeqSingleR <- SingleR(test = MergedData, ref = mouse.rnaseq, assay.type.test=1, labels = mouse.rnaseq$label.main) 
SeqSingleR

MergedData is a Seurat object. But when I run this code, I get this following error:

Error in `rownames<-`(`*tmp*`, value = tolower(rownames(ref_data))) : 
  attempt to set 'rownames' on an object with no dimensions

**Comment by dtm2451** [comment]
See https://github.com/LTLA/SingleR/issues/145#issuecomment-692311765
`test` cannot receive a Seurat object directly.

**Comment by sivaraja23** [comment]
> See [#145 (comment)](https://github.com/LTLA/SingleR/issues/145#issuecomment-692311765) `test` cannot receive a Seurat object directly.

I just tried this method and for some reason it is giving me the same error. I am not too sure where I could have gone wrong

**Comment by dtm2451** [comment]
Is `mouse.rnaseq` an SCE or a Seurat?  If it's a Seurat, then you should use the same function for this `ref` as well.

**Comment by sivaraja23** [comment]
mouse.rnaseq is neither  I believe. Its a built-in reference database from the SingleR package, its just a list of references.

**Comment by sivaraja23** [comment]
![image](https://user-images.githubusercontent.com/53981762/161407343-e8cb8dc8-ba2e-4815-a261-80fd40014ad4.png)
I fixed thar issue but I am getting a new issue with my code and I am not too sure what to do.
