### ISSUE TITLE
SingleR issue

### ISSUE THREAD

**Issue by sivaraja23** [LTLA/SingleR#219]
Hey Guys! I have been stuck on this issue for the past couple of days. I am not too sure where I could have gone wrong. I followed alll the steps required, and any advice would be appreciated. 
![Github](https://user-images.githubusercontent.com/53981762/161467255-6c849ad1-a325-4036-abde-e49b4256491e.jpg)

**Comment by LTLA** [comment]
You should look at what `GetAssayData` produces. `SingleR` is expecting some kind of matrix, e.g., ordinary matrix, `dgCMatrix`.

**Comment by sivaraja23** [comment]
> You should look at what `GetAssayData` produces. `SingleR` is expecting some kind of matrix, e.g., ordinary matrix, `dgCMatrix`.

![32FF7C02-6A9A-47D1-B79F-F52491CC647D](https://user-images.githubusercontent.com/53981762/163310259-abea7f44-52bc-4e35-b7b0-3f5f5fe01a5c.jpeg)

This is what the function getAssayData gets me. I’m not sure what to do

**Comment by LTLA** [comment]
I have no idea. This all works fine for me.

```r
library(scRNAseq)
test <- ZeiselBrainData()
mat <- as(assay(test), "dgCMatrix")

library(celldex)
ref <- MouseRNAseqData()

library(SingleR)
res <- SingleR(mat, ref, labels = ref$label.main)
```

Make sure you're using the latest version. BioC's on 1.8.1.
