### ISSUE TITLE
Errors in creating pred.hesc

### ISSUE THREAD

**Issue by rustylakeparadox** [LTLA/SingleR#220]
Hello, when I was executing the following scripts:

pred.hesc <- SingleR(test = sce_for_SingleR, ref = hpca.se, 
                     labels = hpca.se$label.main,
                     method = "cluster", clusters = clusters, 
                     assay.type.test = "logcounts", assay.type.ref = "logcounts")

Error in rownames(sc_data) : 
  argument "sc_data" is missing, with no default

could you tell me what's the problem? thanks

**Comment by johnnyyq01** [comment]
Did you solve the problem? I have the same problem, could you tell me the solution

**Comment by rustylakeparadox** [comment]
> Did you solve the problem? I have the same problem, could you tell me the solution

hello! For me this problem is simply because of the edition of "SingleR", the current edition I use is 1.8.1.

you can try updating "SingleR" and see if this problem will be solved.
