### ISSUE TITLE
Error in nn.d^2 : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by GHAStVHenry** [LTLA/SingleR#23]
test and ref are SingleCellExperiment from seurat objects

```
scDWSpr <- as.SingleCellExperiment(ref)
sc10x.se <- as.SingleCellExperiment(test)
```

filtered by common genes
```
common <- intersect(rownames(sc10x.se),rownames(scDWSpr))
scDWSpr <- scDWSpr[common,]
sc10x.se <- sc10x.se[common,]
```

```
singler <- SingleR(sc10x.se,ref=scDWSpr,labels=scDWSpr$ident)
```
...gives error:
>Error in nn.d^2 : non-numeric argument to binary operator
In addition: Warning message:
In (function (jobs, data, centers, info, distance, k, query, get.index,  :
  tied distances detected in nearest-neighbor calculation

**Comment by LTLA** [comment]
Make sure you're using BiocNeighbors 1.1.5 ([link](https://bioconductor.org/packages/devel/bioc/html/BiocNeighbors.html)).

**Comment by GHAStVHenry** [comment]
was using 1.2.0, will try version 1.1.5

**Comment by GHAStVHenry** [comment]
I can't seem to get 1.1.5 installed. 1.2.0 is the version in the current version of bioconductor and trying to install from the previous version of bioconductor tries to install version 1.0.0 and it fails because it reacquires R version 3.5... but I am running in 3.6.1 (as I believe is required).

Am I missing a way to install 1.1.5?

**Comment by LTLA** [comment]
Got confused, I should have said 1.3.3. The link contains the instructions.

**Comment by GHAStVHenry** [comment]
yep, installed 1.3.3 and same error

**Comment by LTLA** [comment]
Are you sure? Make sure you restart R after you reinstall.

**Comment by GHAStVHenry** [comment]
Restart seemed to have worked... running now... but it's a large dataset so it'll probably take a while...

I'm not familiar with BiocParallel, I'm running it on a 24 core node of my cluster so I added:
```BPPARAM=MulticoreParam(workers=20)```
sound right?

will see outcome tomorrow morning and report...

Thanks!

**Comment by LTLA** [comment]
For clusters, it's hard to say. Depends on whether you asked for 20 cores; on whether the system enforces limits on the number of cores; if not, whether you have noisy neighbors, and so on.

@j-andrews7 gets through 100k cells in 16 minutes (with the HPCA reference? Can't remember.) on one core so it might be faster than you think, depending on the size of the reference.

IMO, if you're planning to work with large jobs in the cluster via _BiocParallel_, it's worth investing the time to set up `BatchtoolsParam`. It does require a bit of patience to set up the first time, but then it uses your cluster's job scheduler directly and is _the_ way to parallelize R code across hundreds of nodes.

**Comment by GHAStVHenry** [comment]
I have access to all 24 cores, on the older version of singler, I found that I could only use about half of what was available or it would stall out. Using 20 workers here, seemed to work here, I don't know if it actually used 20 cores though.

Well it worked, I'm glad to know the speed has been increased that much, I have more to do today, so I will actually see how long it takes.

THANKS!!!

**Comment by j-andrews7** [comment]
Yeah, it was 100k cells in ~15 minutes, but that was with `method="cluster"`. It was still under an hour with `method="single"` though.

**Comment by GHAStVHenry** [comment]
It's blazing fast, the same data which used to take 4+hrs (on single) before take <5mins on cluster, and maybe <20mins on single now.

I am doing it with ```BPPARAM=MulticoreParam(workers=20)``` (I'm still not sure it that is doing what I think it's doing, but I've left it in there)

The previous version I did: ```numCores=10``` (anything higher would stall out)

Thanks a lot!
