### ISSUE TITLE
Parallel computing fails on HPC cluster

### ISSUE THREAD

**Issue by royfrancis** [LTLA/SingleR#230]
I am running SingleR something like below on a unix HPC cluster.

```
library(celldex)
library(scater)
library(SingleR)
library(BiocParallel)
bp <- MulticoreParam()

ref <- celldex::HumanPrimaryCellAtlasData()
pred <- SingleR(test=GetAssayData(su,slot="data",assay="RNA"),ref=ref,labels=ref$label.main,BPPARAM=bp)
```
My job has access to 1 node which has 20 cores. Each core has 6.4GB RAM.

But, I get the following error:

```
Error in result[[njob]] <- value :
  attempt to select less than one element in OneIndex
Calls: SingleR ... FUN -> bplapply -> bplapply -> bploop -> bploop.lapply
In addition: Warning message:
In parallel::mccollect(wait = FALSE, timeout = 1) :
  1 parallel job did not deliver a result
Execution halted
```

The same code seems to work fine when I run it locally on my linux multicore machine.

I have tried all the following variations on the cluster:

```
bp <- MulticoreParam()
bp <- MulticoreParam(workers=20)
bp <- MulticoreParam(workers=18)
bp <- SnowParam(workers=18, type="SOCK")
```

They all fail. Wondering if something is wrongly specified? Also not sure if this is a SingleR issue or a BiocParallel issue.

```
R version 4.0.4
SingleR_1.4.1
BiocParallel_1.24.1 
```

**Comment by LTLA** [comment]
Hm. That cryptic error message is usually a symptom of a child job being killed. On my HPC, I often see this when I run out of memory somewhere, the child process is killed, and then you get a "did not deliver a result".

Possibly not immediately helpful to you, but the BioC-devel version of **SingleR** performs parallelization at the C++ level. This should greatly improve memory efficiency as we avoid fighting R's garbage collector across multiple processes.
