### ISSUE TITLE
BiocParallel errors

### ISSUE THREAD

**Issue by antoine4ucsd** [LTLA/SingleR#233]
Hello 
I am eager to try SingleR to identify cell subset from scRNAseq data.
I followed this tutorial
https://bioconductor.org/packages/devel/bioc/vignettes/SingleR/inst/doc/SingleR.html
but I get an unusual error:

```
library(SingleR)
pred.hesc <- SingleR(test = hESCs, ref = hpca.se, assay.type.test=1,
    labels = hpca.se$label.main)

```

gives me:
```
Error: BiocParallel errors
  1 remote errors, element index: 1
  2 unevaluated and other errors
  first remote error:
Error: BiocParallel errors
  0 remote errors, element index: 
  25 unevaluated and other errors
  first remote error:
```
I am using a Mac (last gen)

thank you!

**Comment by LTLA** [comment]
Nothing obvious comes to mind. I just ran it on my own computer and it works fine. Make sure you're using the latest version of all packages (i.e., using BioC 3.16, no issues from `BiocManager::valid()`).

**Comment by antoine4ucsd** [comment]
thank you. I figured it may be a Mac issue . I have BioC 3.15 installed. I will update it 
I am attaching my session info if you can find anything else obvious

[session info.txt](https://github.com/LTLA/SingleR/files/10369777/session.info.txt)

**Comment by antoine4ucsd** [comment]
Also if I may
I am trying to identify human brain cells (microglia, astrocyte, neurons, dendritic cells, etc) that are also likely mixed with endothelial cells and probably T cells and some other immune cells.
If I use the BlueprintEncodeData ref alone or combined with HumanPrimaryCellAtlasData, I mostly recover monocytes but NO microglial cells.... is there a better combined atlas to use for such samples?
I also try clustifyr package and it  find mostly microglial cells...
Such different results are intriguing.

I just ran

**Comment by antoine4ucsd** [comment]
and great news. It finally worked after updating to BioC 3.16 and all related packages...
I am still unsure why all cells are identified as mostly monocytes since they are predominiantly microglial cells. if you could advise on the best combined atlas to build, that would be great!

```
ref <- BlueprintEncodeData()
pred <- SingleR::SingleR(test=mydata, ref=ref, labels=ref$label.main)


```
resulting in:
```
   Adipocytes           B-cells      CD8+ T-cells                DC Endothelial cells      Erythrocytes       Fibroblasts 
                8                 8                 2               416                62                 9                 1 
              HSC       Macrophages         Monocytes       Neutrophils          NK cells 
                2               553              1068                 2                 4 
```

**Comment by LTLA** [comment]
Neither of those two references have "microglia", so it's not a surprise that they aren't found.

I don't have much experience with neuronal references, but you could probably make your own from the classic `scRNAseq::ZeiselBrainData`. You should be able to do something like:

```r
zeisel <- scRNAseq::ZeiselBrainData()
zeisel <- scuttle::logNormCounts(zeisel)
ref <- aggregateReference(zeisel, zeisel$level1class) # or level2class
```

and then use that as a reference. Possibly you would want to throw in `BlueprintEncode` as another reference (see [here](http://bioconductor.org/books/release/SingleRBook/using-multiple-references.html)), as the Zeisel dataset doesn't contain any coverage for immune types.

**Comment by antoine4ucsd** [comment]
I will give it a try and let you know how it works!
Much appreciated.

**Comment by antoine4ucsd** [comment]
still not what I would expect. mostly pyramidal CA1 (?)
I will keep looking for other sources but all advices are welcome.

```

astrocytes_ependymal    endothelial-mural            microglia        pyramidal CA1 
                  35                    5                   98                 1997 
```

**Comment by LTLA** [comment]
I'd suggest that you look into some of the diagnostics, e.g., [here](http://bioconductor.org/books/release/SingleRBook/annotation-diagnostics.html#based-on-marker-gene-expression).

**Comment by antoine4ucsd** [comment]
on it
thank you for being so responsive.

**Comment by antoine4ucsd** [comment]
It works well with a new combined ref DarmanisBrainData and HumanPrimaryCellAtlasData
thank you again for your assistance.

**Comment by Roner2022** [comment]
hello，
I am eager to try SingleR to identify cell subset from scRNAseq data.

cellpred <- SingleR(test = testdata,  
                    ref = refdata, 
                    labels = refdata$label.main,
                    method = "cluster", 
                    clusters = clusters,
                    assay.type.test = "logcounts", 
                    assay.type.ref = "logcounts")
but I get an unusual error:
Error: BiocParallel errors
  1 remote errors, element index: 1
  0 unevaluated and other errors
  first remote error:
Error in .read_block_OLD(x, viewport, as.sparse = as.sparse): ### could not find function ".read_block_OLD"

**Comment by LTLA** [comment]
Make a new issue, don't keep reviving old threads.
