### ISSUE TITLE
Viewing the classification genes

### ISSUE THREAD

**Issue by antoine4ucsd** [LTLA/SingleR#234]
Hello 
is there a simple way to view the genes that were used to classify/annotate the cells 
Garnett package has a function get_feature_genes that seems interesting. is there an equivalent in SingleR?
https://cole-trapnell-lab.github.io/garnett/docs/#2-classifying-your-cells

```
feature_genes <- get_feature_genes(pbmc_classifier,
                                   node = "root",
                                   db = org.Hs.eg.db)
head(feature_genes)

#                B cells       T cells      Unknown
#(Intercept) -6.51829349  2.6403157858  3.877977704
#CD74         0.04660324 -0.0529185035  0.006315261
#MS4A1        2.42667982 -2.2194139450 -0.207265871
#CD19         4.33990156 -2.4210500042 -1.918851560
#CD79A        1.09667783 -0.7008461805 -0.395831654
#IGLL5       -0.00103241 -0.0001045559  0.001136966
```

thank you!

**Comment by LTLA** [comment]
Should be somewhere in the `metadata(<DataFrame>)` of the `DataFrame` returned by `SingleR()`. Can't remember the exact name, though. Maybe it's `metadata(<DataFrame>)$markers`.

**Comment by antoine4ucsd** [comment]
checking now. thank you

**Comment by antoine4ucsd** [comment]
I confirm! thank you so much

**Comment by antoine4ucsd** [comment]
metadata(DATAFRAME)$de.genes

**Comment by antoine4ucsd** [comment]
sorry

**Comment by j-andrews7** [comment]
See the appropriate section of [the book](http://bioconductor.org/books/release/SingleRBook/annotation-diagnostics.html#based-on-marker-gene-expression):

```
all.markers <- metadata(pred.grun)$de.genes
beta.markers <- unique(unlist(all.markers$beta))
```

**Comment by antoine4ucsd** [comment]
thank you (again)
