### ISSUE TITLE
runtime for SingleR

### ISSUE THREAD

**Issue by gebdu** [LTLA/SingleR#239]
Hi,

I am annotating my scRNAseq data (Seurat object)

An object of class Seurat 
41445 features across 29902 samples within 1 assay 
Active assay: RNA (41445 features, 1850 variable features)
 4 dimensional reductions calculated: pca, tsne, umap, harmony

Using a reference data:

https://cellxgene.cziscience.com/collections/48259aa8-f168-4bf5-b797-af8e88da6637
https://cellxgene.cziscience.com/collections/48259aa8-f168-4bf5-b797-af8e88da6637
Publication: Khaled et al. (2023) bioRxiv
https://www.biorxiv.org/content/10.1101/2023.04.21.537845v2

Dataset	Tissue	Disease	Assay	Organism	Cells
HBCA - epithelial	breast	normal	10x 3' v3	Homo sapiens	353167

Level2 annotation, that has folloing 13 types of cells
Levels: BSL1 BSL2 DDC1 DDC2  HS1 HS2 HS3 HS4 LP1 LP2 LP3 LP4 LP5

With following command:

ourSCE <- as.SingleCellExperiment(Combined)
refSCE <- as.SingleCellExperiment(myRef)

main <- SingleR(test = ourSCE, 
                  ref = refSCE, 
                  labels = refSCE$level2,
                  assay.type.test = "logcounts", 
                  assay.type.ref = "logcounts",
                  num.threads = 30)

It is running for 5 days, and  it is the "genome-shell" using maximum 200% processor (in top command from a terminal)... an no R. Looks like it is using at best 2 processors. 
So, I just wonder 

-- is it normal that it would take such a long time?
-- is it normal that it would not take all 30 processors?
-- is there anything I can do to speed up the process.

From the same data-set, when I took the Level1 annotation (only 3 cell types), the analysis ended in 24 hours. Now it is taking so long and no clue when it may end.

could you help on this to speed up.

I also tried following way:

library(BiocParallel)
bp <- MulticoreParam(workers=30)
main <- SingleR(test = ourSCE, 
                  ref = refSCE, 
                  labels = refSCE$level2,
                  assay.type.test = "logcounts", 
                  assay.type.ref = "logcounts",
                  BPPARAM = bp)

but thing is same. not using more than 200% cpu.

Thanks for any help.

> ourSCE
class: SingleCellExperiment 
dim: 41445 29902 
metadata(0):
assays(3): counts logcounts scaledata
rownames(41445): ATAD3B ENSG00000228037 ... LINC01690 ABCC13
rowData names(0):
colnames(29902): WT1_AAACCCAAGACATCCT-1 WT1_AAACCCAAGAGTTGAT-1 ...
  OA2_TTTGTTGCAAATACAG-1 OA2_TTTGTTGTCTGTGCGG-1
colData names(13): orig.ident nCount_RNA ... seurat_clusters ident
reducedDimNames(4): PCA TSNE UMAP HARMONY
mainExpName: RNA
altExpNames(0):

> refSCE
class: SingleCellExperiment 
dim: 34535 349497 
metadata(0):
assays(2): counts logcounts
rownames(34535): MIR1302-2HG OR4F5 ... ENSG00000278817 PRODH
rowData names(0):
colnames(349497): TTGCATTCAAGAATGT-SLX-20005_SIGAH12
  GTGATGTTCTGCCCTA-SLX-19902-20449_SIGAB11 ...
  GTGCGTGTCTCTGAGA-SLX-19864-20262_SIGAC6
  TTCTCTCTCAAGCCCG-SLX-19902-20449_SIGAG2
colData names(46): sampleID sample_type_coarse ... nFeature_RNA ident
reducedDimNames(3): DIFFMAP SCVI UMAP
mainExpName: RNA
altExpNames(0):

> > sessionInfo()
R version 4.2.2 (2022-10-31)
 Seurat_4.3.0

SingleR_2.0.0

**Comment by LTLA** [comment]
Not sure why it's only taking 2 CPUs, but when the reference data is large, you may consider setting `aggr.ref = TRUE`. Check out [here](http://bioconductor.org/books/release/SingleRBook/sc-mode.html#pseudo-bulk-aggregation) for more details.
