### ISSUE TITLE
Should `trainSingleR()` make use of log-transformed P-values?

### ISSUE THREAD

**Issue by PeteHaitch** [LTLA/SingleR#241]
`trainSingleR()` when run with `de.method = "wilcox"` or `de.method = "t"` will ultimately call `scran::pairwiseWilcox()` or `scran::pairwiseTTests()`, each with the default value of `log.p = FALSE`, and then pass the result to `scran::getTopMarkers()`.

https://github.com/LTLA/SingleR/blob/6b057e59f35cd1927164ebfc0903040de3c80b56/R/trainSingleR.R#L336-L354

As noted in `?scran::combineMarkers`, "log-transformed p-values ... may be useful in over-powered studies with many cells, where directly reporting the raw p-values would result in many zeroes due to the limits of machine precision."

I find myself in this position in attempting to use a single-cell dataset as a reference with `trainSingleR()`.
Following https://bioconductor.org/books/release/SingleRBook/sc-mode.html, I want to use the Wilcoxon rank sum test for marker detection (`trainSingleR(ref, labels = ref$label, de.method = "wilcox", aggr.ref = TRUE)`) but this results in many features with a P-value of 0.

With this reference dataset, the problem is that `trainSingleR()` then effectively gives me the _first_ `de.n` features with a P-value of 0 (where 'first' means by row order in the test dataset) which is missing out some 'more important' features that happen to be towards the last few rows of the test dataset.

I think that using log-transformed P-values may help here by giving more precise P-values and thus allowing a more accurate ordering of the features.
Does that sound right?

For this reference dataset I think I can achieve what I want by doing the marker gene detection manually with `scran::pairwiseWilcox()` and `scran::getTopMarkers()` and then supplying this to `genes` in `trainSingleR()`, but I wonder if `trainSingleR()` should just always use log-transformed P-values for its internal calculations?

**Comment by LTLA** [comment]
Probably not a bad idea.

TBH I was hoping to switch to `scran::scoreMarkers`, where the ranking by effect size would be simpler. But I don't have the time/inclination to test whether that would be better/worse than the current implementation, so your suggestion is probably easiest for now.

Should be an easy PR if you can make the edit.

**Comment by PeteHaitch** [comment]
Will send a PR once I've settled on my strategy for this particular analysis.

**Comment by PeteHaitch** [comment]
Closed by #243
