### ISSUE TITLE
BiocParallel errors：could not find function ".OLD_read_block"

### ISSUE THREAD

**Issue by alopehba** [LTLA/SingleR#244]
```
library(SingleR)
library(celldex)
library(pheatmap)
library(BiocParallel)
load('ref_Human_all.RData')
ref<-ref_Human_all
singler <- SingleR(test = scRNA_harmony@assays$RNA@data,
                   ref = ref,
                   labels = ref$label.fine, 
                   clusters = scRNA_harmony@meta.data$seurat_clusters)
```
and then
```
Error: BiocParallel errors
  1 remote errors, element index: 1
  4 unevaluated and other errors
  first remote error:
Error in .OLD_read_block(x, viewport, as.sparse = as.sparse): could not find function ".OLD_read_block"
```

I don’t know where the problem is. I checked the data and there is no problem. SingleR’ version 2.2.0, celldex’ version 1.10.1, ‘BiocParallel’ version 1.34.2, all of them are the latest stable version, but the error is still reported.

**Comment by LTLA** [comment]
Nothing comes to mind, I'm afraid. If I had to guess, I'd say your **DelayedArray** installation is either out of date or too new. Try running `BiocManager::valid()` and see if it detects any problems with your system.
