### ISSUE TITLE
could not find function "CreateSinglerObject"

### ISSUE THREAD

**Issue by coconutll** [LTLA/SingleR#245]
library(SingleR)
counts<-pbmc@assays$RNA@counts
clusters<-pbmc@meta.data$seurat_clusters
ann=pbmc@meta.data$orig.ident
singler = CreateSinglerObject(counts, annot = ann, "pbmc", min.genes = 0,
  species = "Human", citation = "",
  ref.list = list(), normalize.gene.length = F, variable.genes = "de",
  fine.tune = F, do.signatures = T, clusters = clusters, do.main.types = T,
  reduce.file.size = T, numCores = 1)

and then

Error in CreateSinglerObject(counts, annot = ann, "pbmc", min.genes = 0,
 object 'CreateSinglerObject' not found

I'm sorry to bother you. After consulting the information, I found that it seems to be a version problem, I do not know where to download the package with this function, or what function can be replaced with this function in the current version. I'm looking forward to your response.

**Comment by LTLA** [comment]
`CreateSingleRObject` hasn't existed in the package for several years. I don't know what documentation you're following, but consider reading the instructions in the [book](https://bioconductor.org/books/release/SingleRBook/).
