### ISSUE TITLE
error when running SingleR

### ISSUE THREAD

**Issue by mimisikai** [LTLA/SingleR#252]
I've observed significant updates to the SingleR function and its variables. Could you update your vignettes accordingly? I'm encountering errors and am unsure if these are due to compatibility issues or incorrect variable usage.

`> pred_perCluster_hpca_bpe = SingleR(sc_data = as.SingleCellExperiment(ImmuneClusters_integrated), 
+                                    ref_data = hpca_bpe_combined, 
+                                    types = hpca_bpe_combined$label.fine,  
+                                    clusters = ImmuneClusters_integrated@meta.data$CellType_Level2)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': no method for coercing this S4 class to a vector`

**Comment by LTLA** [comment]
I am not aware of any version of Bioconductor's **SingleR** that has used `ref_data` or `types` as argument names. AFAIK they have always been `ref` and `labels`, so I don't know what documentation you're reading.

**Comment by mimisikai** [comment]
![Screenshot 2023-11-30 at 11 49 34 AM](https://github.com/LTLA/SingleR/assets/4881411/8f7a8dc9-7cb9-4f91-858d-a7c9de614da0)
SingleR_1.0.1

**Comment by mimisikai** [comment]
`> pred_perCluster_hpca_bpe = SingleR::SingleR(test = as.SingleCellExperiment(ImmuneClusters_integrated), 
+                                    ref = hpca_bpe_combined, 
+                                    labels = hpca_bpe_combined$label.fine,  
+                                    clusters = ImmuneClusters_integrated@meta.data$CellType_Level2,
+                                    assay.type.test = 1)
Error in SingleR::SingleR(test = as.SingleCellExperiment(ImmuneClusters_integrated),  : 
  argument "sc_data" is missing, with no default`

**Comment by LTLA** [comment]
I don't know where that screenshot comes from. `?SingleR` gives me:

```
SingleR                package:SingleR                 R Documentation

Annotate scRNA-seq data

Description:

     Returns the best annotation for each cell in a test dataset, given
     a labelled reference dataset in the same feature space.

Usage:

     SingleR(
       test,
       ref,
       labels,
       method = NULL,
       clusters = NULL,
       genes = "de",
       sd.thresh = 1,
       de.method = "classic",
       de.n = NULL,
       de.args = list(),
       aggr.ref = FALSE,
       aggr.args = list(),
       recompute = TRUE,
       restrict = NULL,
       quantile = 0.8,
       fine.tune = TRUE,
       tune.thresh = 0.05,
       prune = TRUE,
       assay.type.test = "logcounts",
       assay.type.ref = "logcounts",
       check.missing = TRUE,
       num.threads = bpnworkers(BPPARAM),
       BNPARAM = NULL,
       BPPARAM = SerialParam()
     )
     
Arguments:

    test: A numeric matrix of single-cell expression values where rows
          are genes and columns are cells. Alternatively, a
          SummarizedExperiment object containing such a matrix.

     ref: A numeric matrix of (usually log-transformed) expression
```

And this has always been the case in Bioconductor's **SingleR**, e.g., see the [manpage](https://raw.githubusercontent.com/LTLA/SingleR/RELEASE_3_10/R/SingleR.R) for the first release versions (1.0.*).

I assume you are looking at some documentation for the original [**SingleR** repository](https://github.com/dviaran/SingleR), before it was rewritten for submission to Bioconductor. I'm not responsible for that repository or any of its associated documentation.
