### ISSUE TITLE
Cell Type abbreviation of ImmGenData

### ISSUE THREAD

**Issue by Jammm11** [LTLA/SingleR#253]
Hello! 
Thank you for developing such useful tools. I'm wondering if there is a reference of the abbreviation used in presenting the cell types.
I was confused for these subtypes: B cells (B.Fo), B cells (B.FrE), B cells (B.T1), B cells (preB.FrD), B cells (B.B1A), and et al.
Thanks!

**Comment by LTLA** [comment]
I'm afraid I don't really know, but poking around some ImmGen resources (e.g., Figure 1 of the [paper](https://www.immgen.org/img/ImmGenPublications/nihms393618.pdf)) indicates that B.Fo = follicular B cells, and so on.  Perhaps @j-andrews7 or @dtm2451 might have some more insights.

**Comment by j-andrews7** [comment]
Yeah, I'm not sure either. I know I struggled at the time as well. The ontology terms may yield a hint though, it's possible I dug around deeper at some point to figure them out.

**Comment by dviraran** [comment]
Its all here https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE15907
