### ISSUE TITLE
JoinLayers function for Seurat Object for annotation with SingleR

### ISSUE THREAD

**Issue by LeaLe88** [LTLA/SingleR#254]
Dear all,

I have the following issue: I have a Seurat object with 7 layers of raw gene expression counts for 7 different patients.

In order to annotate the object with SingleR I have now used the function "JoinLayers" to combine all counts into one layer of counts of all patients together. I was able to annotate the clusters of cells with

```
kid.filtered_new<- JoinLayers(kid.filtered)

pbmc_counts_combined <- GetAssayData(kid.filtered_new, slot = 'counts')

pred_combined <- SingleR(test = pbmc_counts_combined,
        ref = ref,
        labels = ref$label.main)

kid.filtered_new$singleR.labels <- pred_combined$labels[match(rownames(kid.filtered_new@meta.data), ro```
wnames(pred_combined))]`

DimPlot(kid.filtered, reduction = 'umap', group.by = 'singleR.label`s')
```

However, I would like to use for the annotation not the labels of every cell. Instead I would like to use for the annotation the seurat clusters:

![image](https://github.com/LTLA/SingleR/assets/71077063/9bfedd2d-176d-4e3e-916d-8088f4e784db)

I am able to clusters them by Seurat clusters but the annotation via SingleR was done per single cell. How can I get the annotation done per seurat clusters?

`DimPlot(kid.filtered, reduction = 'umap', group.by = 'singleR.labels')`
I tried this but it is giving me an error:
```

pred_combined <- SingleR(test = pbmc_counts_combined,
        ref = ref,
        labels = ref$label.main, clusters='seurat_clusters')

Error in compute_ugroup(group, ncol(x), reorder) : 
  incorrect length for 'group'
```

Thank you for any input!

**Comment by LeaLe88** [comment]
Hi Andrew, thank you so much for your response.

I have tried what you suggested. Unfortunately, the column singleRlabels remains empty when doing so.. (however no error as before).

Please find below my code:
```

#Annotation by Seurat clusters 
pbmc_counts_combined <- GetAssayData(kid.filtered_new, layer ='counts')

pred_combined <- SingleR(test = pbmc_counts_combined,
        ref = ref,
        labels = ref$label.main, clusters=kid.filtered_new$seurat_clusters)

kid.filtered_new$singleR.labels <- pred_combined$labels[match(rownames(kid.filtered_new@meta.data), rownames(pred_combined))]
```
Please also find a Screenshot below:
![image](https://github.com/LTLA/SingleR/assets/71077063/e619868f-7c39-4f18-9fb3-a69bbebedf6a)


The column singleRlabels is filled with this code (only difference in above I added **clusters=kid.filtered_new$seurat_clusters:**

```
#Annotation by single_cell labels
pbmc_counts_combined <- GetAssayData(kid.filtered_new, layer ='counts')

pred_combined <- SingleR(test = pbmc_counts_combined,
        ref = ref,
        labels = ref$label.main)

kid.filtered_new$singleR.labels <- pred_combined$labels[match(rownames(kid.filtered_new@meta.data), rownames(pred_combined))]
```

**Comment by j-andrews7** [comment]
Yes, that is quite likely the case. If all of those "endothelial" populations are much more similar to that cell type in the reference than the other cell types, they will get assigned to it. 

Try to find a more comprehensive/granular reference that's applicable to your data for finer labeling.

**Comment by LeaLe88** [comment]
Thank you @j-andrews7 I will try to find a better reference!
