### ISSUE TITLE
Annotation of integrated counts

### ISSUE THREAD

**Issue by LeaLe88** [LTLA/SingleR#257]
Dear all, 

Can you please clarify how I should annotate integrated counts?

I have a batch effect in my data and I am therefore performing integration.

I am facing issues when trying to annotate the new clusters after integration as I understand I shouldnt use the integrated counts?

https://www.biostars.org/p/442514/

If I am unable to annotate the new clusters the integration seems not very useful for me?!?

Thank you very much!

**Comment by LTLA** [comment]
Check out the discussion at #129, maybe also #98.

**Comment by LeaLe88** [comment]
Thank you, I will check these discussions!
