### ISSUE TITLE
SingleR - "sc_data" is missing

### ISSUE THREAD

**Issue by nitinmahajan20** [LTLA/SingleR#265]
I am having issue running the Single R (2.4.1) , not sure why I am getting the error. Please help

```
seurat_integrated
```

An object of class Seurat
51866 features across 54453 samples within 3 assays
Active assay: RNA (24468 features, 0 variable features)
2 layers present: data, counts
2 other assays present: SCT, integrated
2 dimensional reductions calculated: pca, umap

```
ref <- celldex::HumanPrimaryCellAtlasData()
seurat_integrated_counts <- GetAssayData(seurat_integrated, layer = 'counts')

pred <- SingleR(test = seurat_integrated_counts,
        ref = ref,
        labels = ref$label.main)

pred
```

ERROR

```
Error in SingleR(test = seurat_integrated_counts, ref = ref, labels = ref$label.main) :  argument "sc_data" is missing, with no default

**Comment by j-andrews7** [comment]
See #249. Without `sessionInfo()`, my guess is this is related to either an old R version, old SingleR version (though you say you're using the most current, so presumably not that), or some issue in a dependency, as `sc_data` is not found anywhere in the SingleR codebase.

**Comment by jboktor** [comment]
I am seeing this same error.
