### ISSUE TITLE
SingleR: GetAssayData doesn't work for multiple layers in v5 assay

### ISSUE THREAD

**Issue by Eos-halo** [LTLA/SingleR#266]
I am having issue running the Single R (2.0.0) . Please help

> pred.scRNA <- SingleR(test = scRNA@assays$RNA@data, 
                      ref = ref,
                      labels = ref$label.main, 
                      clusters = scRNA@active.ident)
Error: GetAssayData doesn't work for multiple layers in v5 assay

**Comment by j-andrews7** [comment]
Seurat data structures and retrieval functions are not under the purview of SingleR. 

Please contact the Seurat devs and view their docs.
