### ISSUE TITLE
plotScoreHeatmap Error

### ISSUE THREAD

**Issue by akhst7** [LTLA/SingleR#31]
HI, 

I created a singleR object from Seurat3 integrated objects by `as.SingleCellExperiment` by;

`ap.int.singler.im<-SingleR(ap.int.sc, ref=immgen.se, labels = immgen.se$label.main, assay.type.ref = "logcounts" )`

Then, I run plotScoreHeatmap() and got a following error;

```
Error in UseMethod("depth") : 
  no applicable method for 'depth' applied to an object of class "NULL"
```
Here is str() of my singleR objects;

```
Formal class 'DFrame' [package "S4Vectors"] with 6 slots
  ..@ rownames       : chr [1:18423] "AAACCCACACTGTGTA_1" "AAACCCACATTAAAGG_1" "AAACCCAGTGCATGTT_1" "AAACCCAGTTAGTTCG_1" ...
  ..@ nrows          : int 18423
  ..@ listData       :List of 4
  .. ..$ scores       : num [1:18423, 1:20] 0.334 0.133 0.246 0.107 0.128 ...
  .. .. ..- attr(*, "dimnames")=List of 2
  .. .. .. ..$ : NULL
  .. .. .. ..$ : chr [1:20] "Macrophages" "Monocytes" "B cells" "DC" ...
  .. ..$ first.labels : chr [1:18423] "Fibroblasts" "Endothelial cells" "Fibroblasts" "Epithelial cells" ...
  .. ..$ tuning.scores:Formal class 'DFrame' [package ""] with 6 slots
  .. .. .. ..@ rownames       : NULL
  .. .. .. ..@ nrows          : int 18423
  .. .. .. ..@ listData       :List of 2
  .. .. .. .. ..$ first : num [1:18423] 0.336 0.34 0.542 0.217 0.115 ...
  .. .. .. .. ..$ second: num [1:18423] 0.0716 0.2805 0.4848 -0.0373 0.1129 ...
  .. .. .. ..@ elementType    : chr "ANY"
  .. .. .. ..@ elementMetadata: NULL
  .. .. .. ..@ metadata       : list()
  .. ..$ labels       : chr [1:18423] "Fibroblasts" "Endothelial cells" "Fibroblasts" "Epithelial cells" ...
  ..@ elementType    : chr "ANY"
  ..@ elementMetadata: NULL
  ..@ metadata       : list()
```
I see two slots having NULL.  I'd appreciate any pointers on this. 

Thanks.

**Comment by dtm2451** [comment]
Hello,

I am having trouble repeating your issue at the moment using the Seurat::pbmc_small dataset.  It's human not mouse but I don't think that species should be the issue.

I also see the same NULLs in the results of my SingleR run.  I think those are unused slots of the structure and meant to be NULL.

Could you send the code that you had used to run plotScoreHeatmap()?

```
hpca.ref <- HumanPrimaryCellAtlasData()
pbmc.se <- as.SingleCellExperiment(Seurat::pbmc_small)
pred <- SingleR(test = pbmc.se,
                ref=hpca.ref,
                labels = hpca.ref$label.fine ,
                assay.type.ref = "logcounts")
plotScoreHeatmap(pred, clusters = pred$labels, max.labels = 20)
```

The code above gives me:

![image](https://user-images.githubusercontent.com/38870347/64060063-889ec300-cb7c-11e9-95c9-db02b8284c74.png)

**Comment by LTLA** [comment]
The `NULL`s in the `DFrame` are unlikely to be the problem.

Some Googling suggests that this is caused by `grid` and that it depends on factors such as how large your plotting window is. See tidyverse/ggplot2#2514 for a discussion.

**Comment by j-andrews7** [comment]
This is indeed a plotting window issue. Easiest way to replicate is to run a plot command in Rstudio and shrink the window size pretty drastically before it displays. Sometimes it may still display, but often throws that error. Increasing the size of the plotting window is typically the fix.

**Comment by akhst7** [comment]
@dtm2451 
 I just used `plotScoreHeatmap(Seurat.ob)` and got an error. My Seurat.ob was fairly big with integration of 5 Seurat objects.   Smaller obs did work. 
![Rplot01](https://user-images.githubusercontent.com/3075799/64189855-23c8be80-ce43-11e9-8c82-9852ecb77e07.png)

A workaround for plotting a large integrated Seurat objects is what @LTLA  and @j-andrews7 suggested.  

Thanks.
