### ISSUE TITLE
Package dependencies origin

### ISSUE THREAD

**Issue by llrs** [LTLA/SingleR#38]
I was trying to follow the vignette when I got an error because scRNAseq does not provide the function `LaMannoBrainData`. I then tried to install `BiocManager::install("LTLA/scRNAseq")`, but again I got an error:

```r
   ERROR: package installation failed
Error: Failed to install 'scRNAseq' from GitHub:
  System command error, exit status: 1, stdout + stderr (last 10 lines):
E> ** R
E> ** data
E> ** inst
E> ** byte-compile and prepare package for lazy loading
E> Error: object ‘splitAltExps’ is not exported by 'namespace:SingleCellExperiment'
E> Execution halted
E> ERROR: lazy loading failed for package ‘scRNAseq’
E> * removing ‘/tmp/RtmpMWKJi7/Rinst290421337ff/scRNAseq’
E>       -----------------------------------
E> ERROR: package installation failed
```

All these errors seems to raise from using different versions of packages for development than those available through Bioconductor or CRAN. I am not using Bioconductor devel.
Are all the dependencies of the package already on Bioconductor devel? Or are there some dependencies on Github? 

(I don't want to move to Bioconductor devel on my system but I would like to run some parts of the vignette) 

Thanks

**Comment by j-andrews7** [comment]
This is indeed due to reliance on bioc-devel versions. This will be made
more clear in the next round of doc updates.

**Comment by llrs** [comment]
I finally did what I wanted without running the code of the vignette. Many thanks.
