### ISSUE TITLE
Bioconda version of SingleR

### ISSUE THREAD

**Issue by hramadas** [LTLA/SingleR#44]
Hello,

Do you have any plans to create a conda version of SingleR? It seems to me like a large number of Bioconductor packages are available via Bioconda, so was wondering if that is something you're planning on.

Thank you - apologies if this is the wrong place to be asking.

Harish

**Comment by LTLA** [comment]
I think it's a pull process rather than a push process, i.e., talk to the Bioconda maintainers.

**Comment by LTLA** [comment]
I'm going to close this unless I'm told to do something.
