### ISSUE TITLE
Not able to download reference data from Bioconductor when using SingleR

### ISSUE THREAD

**Issue by BridgetPK** [LTLA/SingleR#45]
I am trying to use SingleR for analysis of my dataset and hitting a roadblock accessing the reference data. I cannot download within R from Bioconductor due to an expired license. Can you suggest a work around?

hpca.se <- HumanPrimaryCellAtlasData()
```
Error in .util_download(x, rid[i], proxy, config, "bfcadd()", ...) : 
  bfcadd() failed; see warnings()
In addition: Warning messages:
1: download failed
  web resource path: ‘https://experimenthub.bioconductor.org/metadata/experimenthub.sqlite3’
  local file path: ‘/wynton/home/fong/bkeenan/.cache/ExperimentHub/1de062c5e7265_experimenthub.sqlite3’
  reason: Peer's Certificate has expired. 
2: bfcadd() failed; resource removed
  rid: BFC6
  fpath: ‘https://experimenthub.bioconductor.org/metadata/experimenthub.sqlite3’
  reason: download failed 
```

**Comment by j-andrews7** [comment]
This appears to be due to Bioconductor's SSL certificate expiring. It is not something we can fix, but the Bioconductor team is aware of it and working to address it. I will update here when it is resolved.

**Comment by dtm2451** [comment]
Bioconductor's SSL issue seems to be fixed now.  Do you still get the issue?

**Comment by BridgetPK** [comment]
No, still getting same error that certificate is expired.

**Comment by dtm2451** [comment]
Oh I still get it too, sorry.  I'd noticed that bioconductor.org works for me again and I can install packages again using `BiocManager::install()`.

My guess is it there might be separate certificates that needed updating and the Experiment Hub-related certificates are taking a bit longer.  Hopefully this will be corrected soon.

**Comment by dtm2451** [comment]
Try again?  `HumanPrimaryCellAtlasData()` works for me now.

**Comment by BridgetPK** [comment]
Yes, seems to be working now  - thanks.

**Comment by LTLA** [comment]
Closing.
