### ISSUE TITLE
Using SingleR with clustered data

### ISSUE THREAD

**Issue by oli-23** [LTLA/SingleR#46]
Hello, 

I've successfully used the SingleR function to assign cell-types using the "single" method, but am not succeeding with the "cluster" method. The clustering is done in Seurat and the object is imported as a SingleCellExperiment. 

sample.pred.cluster.dice <- SingleR(test = sample.dice.sce, ref = dice.se.common, labels = dice.se.common$label.fine, fine.tune = TRUE, method = "cluster", clusters = "seurat_clusters")

Here is the error: 

Error in .local(x, group, reorder, na.rm, ...) : 
  incorrect length for 'group'

Thanks for your help!

**Comment by LTLA** [comment]
I presume you mean `sample.dice.sce$seurat_clusters`?

**Comment by oli-23** [comment]
Yes

**Comment by LTLA** [comment]
As in, "yes, and it worked now" or "yes, but it still isn't working"?

**Comment by oli-23** [comment]
Sorry for the ambiguous reply. Yes, it worked! Thanks for your quick reply
