### ISSUE TITLE
error: matrix object should have 'dim' attribute when trying to use scanpy data

### ISSUE THREAD

**Issue by BridgetPK** [LTLA/SingleR#50]
Hi,
I am a Scanpy user and trying to export and format my object for use in R and SingleR, struggling since although it says this is applicable to other data formats, most people have used Seurat single cell objects. I am using a csv with rownames of genes, column names of barcodes, subsetted to 100 cells as in the vignette to make it easier to work with ("MyData"). The dimensions of MyData after running
```common <- intersect(rownames(MyData), rownames(hpca.se))
hpca.se <- hpca.se[common,]
MyData <- MyData[common,]
```
are 12501 and 100, as are the dimensions of hpca.se. However, I get the error
```
pred.hpca <- SingleR(test = MyData, ref = hpca.se, labels = hpca.se$label.main)
Error in (function (Exprs, scores, References, quantile, tune_thresh,  : 
  matrix object should have 'dim' attribute
```

Any suggestions for formatting my scanpy data so I can use SingleR?
Thanks,
Bridget

**Comment by LTLA** [comment]
What is `MyData`?

**Comment by BridgetPK** [comment]
It is a matrix of my single cell data that I generated with a pandas dataframe and saved as tsv. Formatted as in my last message - rownames are genes, column names are barcodes of the cells. Is there a better way to generate or format this so that I can use singleR with my scanpy data? Thanks.

**Comment by LTLA** [comment]
I find it hard to believe that `MyData` is actually a matrix. Does `is.matrix(MyData)` return `TRUE`?

**Comment by BridgetPK** [comment]
You are correct; I was able to convert to a matrix and get it working.

Unrelated, but, is there updated code from the older SingleR version to use this to annotate pre-existing clusters vs single cells? 
Thanks!

**Comment by LTLA** [comment]
If you want to annotate cluster-level expression profiles, use `method="cluster"`.

**Comment by LTLA** [comment]
I'm going to assume that this is resolved.
