### ISSUE TITLE
Can't create SummarizedExperiment object 

### ISSUE THREAD

**Issue by LustigePerson** [LTLA/SingleR#52]
Commit I used: e08fcba8a0c87526478f654d612395d15ce1b813

If I try `hpca.se <- SingleR::BlueprintEncodeData()` I get the following error:
```R
Using temporary cache /tmp/RtmpxUy46B/BiocFileCache
snapshotDate(): 2019-04-29
Using temporary cache /tmp/RtmpxUy46B/BiocFileCache
Error in .local(x, i, j, ...): 'i' must be length 1
Traceback:

1. SingleR::BlueprintEncodeData()
2. .create_se(file.path("blueprint_encode", version), assays = "logcounts", 
 .     rm.NA = rm.NA, has.rowdata = FALSE, has.coldata = TRUE)
3. hub[hub$rdatapath == file.path(host, paste0(a, ".rds"))][[1]]
4. hub[hub$rdatapath == file.path(host, paste0(a, ".rds"))][[1]]
5. .local(x, i, j, ...)
6. stop("'i' must be length 1")
```

The same for hpca and the other references. As I can't update to the bioconductor devel I installed this directly from github. Can this be an issue?
Actually I want to apply SingleR to an Seurat object, but I am not quite sure on how. In the old SingleR version I used `CreateSinglerObject` on the Seurat counts....

**Comment by LTLA** [comment]
This is what I get:

```
hpca.se <- SingleR::BlueprintEncodeData()
## snapshotDate(): 2019-10-22
## see ?SingleR and browseVignettes('SingleR') for documentation
## downloading 0 resources
## loading from cache
## see ?SingleR and browseVignettes('SingleR') for documentation
## downloading 0 resources
## loading from cache
```

> As I can't update to the bioconductor devel I installed this directly from github. Can this be an issue?

Yes. There is no guarantee that BioC-devel versions of packages will work with BioC-release versions, as they are designed to operate in cohorts.

> Actually I want to apply SingleR to an Seurat object, but I am not quite sure on how.

See the `README`.

**Comment by LustigePerson** [comment]
Ok, thank you. I will stick with the old SingleR version until there is a stable release of bioconductor with this version in it.
Btw: Is the Version in the old repo more up-to-date? I just noticed the version number there is higher. Or is this totally independent now?

**Comment by LTLA** [comment]
> Ok, thank you. I will stick with the old SingleR version until there is a stable release of bioconductor with this version in it.

This should happen at the end of the month, see https://bioconductor.org/developers/release-schedule/.

> Btw: Is the Version in the old repo more up-to-date? I just noticed the version number there is higher. Or is this totally independent now?

No, the numbers are totally out of sync now. BioC expects incoming packages to be version 0.99.* to fit in with their numbering scheme, hence the lower number.
