### ISSUE TITLE
Applying of Seurat cell-clustering analysis in SingleR

### ISSUE THREAD

**Issue by erikfel97** [LTLA/SingleR#53]
Hi All!
I'm currently working on my first project of Single Cell analysis and it will be great to have your advice.
I did all the necessary analysis of mt data with Surat - including combining 5 data sets, filtering the cells, normalizing and scaling the expression values, etc. I finally cluster the pre-processed data and found 25 cell clusters, now I need to annotate them.
As I understand from the vignette, I should provide SingleR with the counts. Two questions:
1, Is there any option to use the differential expressed marker gene output of Seurat to insure that SingleR analysis will define the same 25 clusters?
2. Which pre-processing is required for the input data?

Best,
Erik

**Comment by LTLA** [comment]
> 1, Is there any option to use the differential expressed marker gene output of Seurat to insure that SingleR analysis will define the same 25 clusters?

There seems to be some misconceptions here. _SingleR_ doesn't do any clustering. Rather, it just uses the precomputed clusters or labels that you provide it.

- If you set `method="single"`, _SingleR_ only cares about the labelling of the **reference** dataset. It doesn't care about the clustering of the **test** dataset, that information is not used at all.
- If you set `method="cluster"`, _SingleR_ will use the clustering of the test dataset to create pseudo-bulk samples and annotate them based on the labels of the reference. This is optional, but if you want to do it, then you can just pass the vector of Seurat-derived cluster identities to `SingleR()`.

> 2. Which pre-processing is required for the input data?

As the vignette suggests, you should have applied quality control to the test data. And that's it. For the test dataset, you can pass the raw counts or the log-transformed normalized counts, it doesn't matter provided you're performing a monotonic transformation within each cell. 

For the reference dataset, you should pass the log-counts if you're relying on `SingleR()`'s in-built marker detection. (This is the default assay for all the in-built references.)

**Comment by erikfel97** [comment]
Thank you very much for your fast response,
Things now much clearer.

Now I'm trying to run the first lines of the code, and every time I try the same error message is coming:
pca.se <- HumanPrimaryCellAtlasData()
Error in HumanPrimaryCellAtlasData() : 
  could not find function "HumanPrimaryCellAtlasData"

Do you have any suggestions?

**Comment by LTLA** [comment]
Are you using the latest [version](https://bioconductor.org/packages/release/bioc/html/SingleR.html)?

**Comment by erikfel97** [comment]
I guess I am, I've tried to solve this problem by re-installing the package...

**Comment by LTLA** [comment]
Well, it helps if you look at your `sessionInfo()` to confirm that you have the right version installed.

Note that re-installing it is not enough. If you are in an R session where you have already loaded some package X, re-installing X will not change the loaded version. In fact, reinstalling and reloading X will not change the loaded version. In general, you have to restart your R session to clear out any loaded packages and then `library(X)` will load in the latest version that you just installed.

**Comment by LTLA** [comment]
I'm going to assume that this was fixed, but if not, check out davismcc/scater#100 for a related issue and its solution.

**Comment by tufeiyinjie** [comment]
Hi, 
I have a error message list below. and my sessioninfo  is listed below. I am a fresher using singleR. I have read the above information, which can't fix my problem. Could you give me some information about that?

Thanks,
Fei

> ref <- celldex::HumanPrimaryCellAtlasData()
snapshotDate(): 2020-04-27
Error in .local(x, i, j = j, ...) : 'i' must be length 1

> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS:   /usr/lib64/libblas.so.3.4.2
LAPACK: /usr/lib64/liblapack.so.3.4.2
