### ISSUE TITLE
Sparse matrix counts support

### ISSUE THREAD

**Issue by j-andrews7** [LTLA/SingleR#6]
When `SingleR()` is passed `SingleCellExperiment` objects with sparse matrixes as `counts` with `method = 'cluster'` and `clusters` defined, a `rowsum` error is thrown. As far as I can tell, nothing is wrong with the count matrix nor the cluster labels. The example code runs fine, and the only difference I can see is that the count matrix for the SCE object there is a base `matrix`, whereas the objects I'm using have sparse matrix formats (`dgCMatrix`). Running with `method = 'single'` works fine. Adding sparse matrix support would be excellent.

To reproduce:
```r
library(Seurat)
library(SingleR)
library(scater)

scrna.sce <- as.SingleCellExperiment(pbmc_small)

hpca <- SingleR::getReferenceDataset(dataset = 'hpca')
common <- intersect(rownames(scrna.sce), rownames(hpca$data))
scrna.sce <- scrna.sce[common,]
scrna.sce <- scrna.sce[,colSums(counts(scrna.sce)) > 0]

scrna.sce <- scater::normalize(scrna.sce)
hpca$data <- hpca$data[common,]

# Works.
pred.hpca2 <- SingleR(test=scrna.sce, training=hpca$data, labels=hpca$main_types, assay.type = 2)

# Throws "rowsum 'x': must be numeric error" at 'colsum(test, clusters)' step of SingleR().
pred.hpca2 <- SingleR(test=scrna.sce, training=hpca$data, labels=hpca$main_types, assay.type = 2, 
  method = "cluster", clusters = as.character(scrna.sce$ident))
```

This can be worked around by manually converting the sparse matrix to a typical matrix and assigning that to counts:

```r
class(counts(scrna.sce))
> 'dgCMatrix'

counts(scrna.sce) <- as.matrix(counts(scrna.sce))
class(counts(scrna.sce))
> 'matrix'

scrna.sce <- scater::normalize(scrna.sce)

# Now works.
pred.hpca <- SingleR(test=scrna.sce, training=hpca$data, labels=hpca$main_types, assay.type = 2, 
                    method = "cluster", clusters = as.character(scrna.sce$ident))
```

The error isn't immediately intuitive and given the performance benefits of sparse matrices, it would be good to look further into this.

**Comment by LTLA** [comment]
Done.
