### ISSUE TITLE
HI Can the new singleR do the same T-sne plot as the old one?

### ISSUE THREAD

**Issue by Midsummer723** [LTLA/SingleR#61]
I used the old version of the singleR. I need the T-sne plot function.
Can the new singleR do the same t-SNE plot as the old one?
And how can I do it? I use the seurat a lot, but I did not have experience to use scater.
Thank you very much.

**Comment by LTLA** [comment]
You can generate a t-SNE plot with any method, the new SingleR just provides the labels. So, you can make a t-SNE plot with Seurat and replace the `ident` field with the SingleR-generated labels. Alternatively, you can use any of the SCE-compatible methods like _scater_ or _dittoSeq_.

It was a deliberate decision to simplify the package in this manner, to avoid reimplementing visualization functionality that was already present in other packages. This makes it easier for users (who don't have to learn **another** visualization function) and for us developers.

I don't remember what the old SingleR used to do for its t-SNE; I'm guessing it just ran Seurat's stuff internally? You're probably doing that anyway, so you can just stick your labels on top of it.

**Comment by Midsummer723** [comment]
HI the old one like this: 
out = SingleR.PlotTsne(singler$singler[[1]]$SingleR.single,
                       singler$meta.data$xy,do.label = F,
                       do.letters = T,labels = singler$meta.data$orig.ident, 
                       dot.size = 1.3,alpha=0.5,label.size = 6)
out$p
Can you give me some code like this so I can use for the visualization for t-sne plot.
Thank you  very much

**Comment by j-andrews7** [comment]
As Aaron already said, you can use whichever t-SNE plotting method is appropriate for your workflow. If you're using Seurat, you can just assign labels and use them for your `DimPlot`:

```
seurat.obj[["SingleR.labels"]] <- singler.results$labels
Seurat::DimPlot(seurat.obj, reduction = "tsne", group.by = "SingleR.labels")
```

A similar approach can be taken with a `SingleCellExperiment` object using `scater` or `dittoSeq` for plotting.

**Comment by LTLA** [comment]
FYI, the equivalent scater code would be something like this:

```r
# Assume we're starting from a SCE with counts:
library(scater)
sce <- logNormCounts(sce)
sce <- runPCA(sce)
sce <- runTSNE(sce, dimred="PCA")

# Assume we ran SingleR on 'sce' with a suitable reference:
sce$labels <- singler.results$labels
plotTSNE(sce, colour_by="labels", text_by="labels")
```

**Comment by Midsummer723** [comment]
It works. I appreciate the help you give me.
Thank a lot!
