### ISSUE TITLE
Index out of bounds when subseting using common geneset

### ISSUE THREAD

**Issue by mbassalbioinformatics** [LTLA/SingleR#67]
Hi, using SingleR v1 from bioconductor.  When using a custom classifier, I run intersect() between the classifer and the set to annotate, but then when running 
```
SingleR(test = logcounts(xxxxx)[ common_genes, ], 
             ref = loaded_classifier[ common_genes, ],
              ....)
```
I get the error
```
Error in SummarizedExperiment:::.SummarizedExperiment.charbound(subset,  : 
  index out of bounds: gene1 gene2 gene3
````
Testing to make sure whether the rownames in the intersect really are in both the classifier and the dataset shows that yes, all rownames are present.  Only when running the SingleR function does an index out of bounds error get thrown.  Thoughts/suggestions??

**Comment by mbassalbioinformatics** [comment]
Nevermind, tracked down the issue.  Apologies

**Comment by AhmedArslan** [comment]
Same error, any suggestions?

**Comment by mbassalbioinformatics** [comment]
This was a while ago so its hard to remember, but it would have been 1 of 2 things
1 - there is a space somewhere at the end of a gene name or something that is causing a lack of a match
2 - check the "type" of the rownames to make sure its comparing text to text

The other thing i'd try is pulling out the structures and try to compare manually and see if you can get it to work, that should give you a better indication where its falling over.
