### ISSUE TITLE
Re-use the download reference

### ISSUE THREAD

**Issue by anyone1985** [LTLA/SingleR#70]
Hi,

I downloaded reference data successfully on a server. I'd like to run SingleR on another server which failed to download the reference data several times. Can I copy the content of ~/.cache/ExperimentHub to the failed server and use the cache in the SingeR? How should I set the option during the running?

Thank you very much.

Best,

Fei

**Comment by LTLA** [comment]
Simplest approach is just to `saveRDS()`, copy the file over to the other server, and then `readRDS()`.

Though the better solution would be to figure out why your other server's downloads aren't working.

**Comment by LTLA** [comment]
I'm going to point to #72 and close this issue.
