### ISSUE TITLE
How to adjust the plot with the plotScoreHeatmap？

### ISSUE THREAD

**Issue by Midsummer723** [LTLA/SingleR#71]
I try to do the plotScoreHeatmap in different ways as the previous version of singleR. as below:
  **SingleR.DrawHeatmap(singler$singler[[1]]$SingleR.single.main, top.n = Inf,
  clusters = singler$meta.data$orig.ident)**
![image](https://user-images.githubusercontent.com/57115292/70439018-5f50d580-1a8f-11ea-8d02-e0fd8aec7c54.png)
And how to show the top 50 cell types which can give me more details  :
SingleR.DrawHeatmap(singler$singler[[1]]$SingleR.single, top.n = 50,
clusters = singler$meta.data$orig.ident)
![image](https://user-images.githubusercontent.com/57115292/70439137-9c1ccc80-1a8f-11ea-867f-d310d91541bc.png)

**Comment by dtm2451** [comment]
Hi @Midsummer723,
You're question is a bit amorphous, but here's what I think you are looking for (?):

To get both fine and main labels, you will need to run SingleR twice, once with each set.  Something like this:

```
hpca.ref <- HumanPrimaryCellAtlasData()
pred.fine <- SingleR(test = data, ref=hpca.ref, labels = hpca.ref$label.fine)
pred.main <- SingleR(test = data, ref=hpca.ref, labels = hpca.ref$label.main)
```
(The old version of SingleR ran both ways by default, but we wanted to give users more obvious control to just run what is needed.)

Then, to make the first heatmap I think you can just use this (but here is where I'm a little unsure what exactly you are asking for):

```
plotScoreHeatmap(pred.fine, clusters = pred.main$labels)
```

For the second heatmap showing more fine labels, use the `max.labels` input:

```
plotScoreHeatmap(pred.fine, clusters = pred.main$labels, max.labels = 50)
```

Please let me know if I answered what you were looking for.

**Comment by Midsummer723** [comment]
Thank you very much for the answer.  
I use the ImmGenData() as references.  However, it just shows the T cells type not more details. 
Could you help me to get more information about that.  It may look like this
![image](https://user-images.githubusercontent.com/57115292/70531805-fbddab00-1b55-11ea-8a2f-5257f5ecfab6.png)

**Comment by dtm2451** [comment]
For your further question, I need to refer you to the associated publication. This is easily obtained from the ImmGenData() documentation that's accessible by running `?ImmGenData`. (Heng TS, Painter MW, Immunological Genome Project Consortium (2008). The Immunological Genome Project: networks of gene expression in immune cells. Nat. Immunol. 9, 1091-1094.)

Your friendly SingleR team works to make useful references easily available, but does not generate the original data ourselves.

**Comment by LTLA** [comment]
I'm going to assume this problem was solved, whatever it was.
