### ISSUE TITLE
CreateSinglerObject function

### ISSUE THREAD

**Issue by saisaitian** [LTLA/SingleR#75]
Hi,

CreateSinglerObject function has been removed ,could you tell me how to do in following code:
```
singler <- CreateSinglerObject(counts=counts,
                               project.name="excelerate course", # choose
                               min.genes = 200, # ignore cells with fewer than 200 transcripts
                               technology = "CEL-Seq2", # choose
                               species = "Human",
                               citation = "Schelker et al. 2017", # choose
                               ref.list = list(hpca=hpca, bpe=blueprint_encode),
                               normalize.gene.length = FALSE,        # needed for full-length
```

**Comment by LTLA** [comment]
There is no longer any need to create a `SingleR` object. Consider reading the new vignette:

https://bioconductor.org/packages/release/bioc/vignettes/SingleR/inst/doc/SingleR.html

**Comment by saisaitian** [comment]
can I use legacy version？

**Comment by LTLA** [comment]
No. 

It's the same algorithm, but easier to use. Just grab your expression matrix, pick your reference, and put them both into `SingleR()` to get the results. No need to create more objects.

**Comment by saisaitian** [comment]
In fact，many ref dataset failed to download，can I use data legacy SingleR package [(https://github.com/dviraran/SingleR/tree/master/data)],  and could you provied me a rdata about DatabaseImmuneCellExpressionData() and ImmGenData() and MonacoImmuneData(). For the three datasets, I always get errors

**Comment by LTLA** [comment]
> can I use data legacy SingleR package [(https://github.com/dviraran/SingleR/tree/master/data)]

You can use whatever you want, but I can only provide guarantees on the correctness and functionality of the latest version (i.e., in this repository or from BioC 3.10).

> could you provied me a rdata about DatabaseImmuneCellExpressionData() and ImmGenData() and MonacoImmuneData().

No, see my comments at the start of #72.

This discussion has getting off-topic, so unless you're going to ask questions related to (the absence of) `CreateSinglerObject`, I will close this issue.
