### ISSUE TITLE
Cannot use Custom References

### ISSUE THREAD

**Issue by davidepisu** [LTLA/SingleR#76]
I have some custom references that I made with the previous version of SingleR.
However when I try to use them with SingleR 1.0.4 from Bioconductor I get the following error:

Error in FUN(X[[i]], ...) : 'ref' must have row names

I tried to look if there's a way to build references using the new version of SingleR, but haven't found much.
Should I stick with the old legacy version?

Thanks!

**Comment by LTLA** [comment]
From `?SingleR`:

```
     ref: A numeric matrix of expression values where rows are genes
          and columns are reference samples (individual cells or bulk
          samples). Each row should be named with the gene name. In
          general, the expression values are expected to be
          log-transformed, see Details.

          Alternatively, a SummarizedExperiment object containing such
          a matrix.

          Alternatively, a list or List of SummarizedExperiment objects
          or numeric matrices containing multiple references, in which
          case the row names are expected to be the same across all
          objects.
```

Seems pretty clear to me.

**Comment by davidepisu** [comment]
I read that. What I didn't understand is where I declare the main labels and the detailed labels for fine-tuning. Previously, I created the list, get the variable genes and use that.
Anyway, I checked the immgen summarized experiment and I see the main types are declared in a slot there. I'll try to follow the same scheme to create my own.

Sorry for the noob questions, I just switched to the new bioconductor version of the package.

**Comment by LTLA** [comment]
I'll assume you've already read through the description of the `labels` argument. 

It is important to note that there's no need to create slots or interact with any S4 structures if you don't want to. Just give `SingleR()` the test matrix of expression values, the reference matrix and a character vector of reference labels. And that's it. No mucking around with custom classes or whatever. You can control the genes by setting `genes=` if you want, but that's optional.

`SingleR()` only ever uses one set of labels. AFAIK, this has always been the case, so even if you gave it 2 sets of labels, any given run of the algorithm would only be using one of them.

**Comment by dtm2451** [comment]
@LTLA Dvir's SingleR actually did used to run versus two sets of labels termed as `main` and `fine`.  Both were reported within the single, far more complicated than our current DataFrame, output.

@davidepisu, to clarify, you can still run SingleR versus both main.labels & fine.labels pretty simply, but the way to do that is with two separate calls:

```
broad.results <- SingleR(..., labels = main.labels)
fine.reesults <- SingleR(..., labels = fine.labels)
```

**Comment by LTLA** [comment]
Yes, that's what I meant in terms of the algorithm (as distinct from the function) only using one set of labels at a time. I think our current set-up is pretty good because (i) the interpretation of the output is much clearer and (ii) people don't have to run the time-consuming fine labels unless they want to.

**Comment by davidepisu** [comment]
Perfect. Thank you to both of you. I figured out. It was very easy. I just got confused about the different approach to the references between the two versions.

**Comment by YiweiNiu** [comment]
Hi, I found that it would get this error if the `logcounts` is a `data.frame`. And change it to 'matrix' would solve this problem in my case
