### ISSUE TITLE
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) :  invalid character indexing

### ISSUE THREAD

**Issue by alexvpickering** [LTLA/SingleR#77]
Happens on this line in `.build_trained_index`:

```R
sr.out <- .scaled_colranks_safe(current[common, , drop = FALSE])
```

In my case, this occurs because `common` is not a subset of `row.names(current)`. This occurs because I passed `genes` in as the result of `scran::getTopMarkers` and then the `ref` SCE gets subset to include genes in common with the `test` SCE.

PR on way.

**Comment by LTLA** [comment]
Closed by #80.
