### ISSUE TITLE
Cellular annotation with multiple references

### ISSUE THREAD

**Issue by namit-k** [LTLA/SingleR#81]
Hi,
When providing a list of references for cellular annotation, are scores from fine tunning considered?

I am trying to annotate cells in a Seurat object against multiple references (BlueprintEncode and HumanPrimaryCellAtlas). Previously, I have noticed ambiguous annotations for Tregs and Tcell-gamma delta cells, presumably since BlueprintEncode doesn't include the Tcell-gamma delta samples.

Reading from the current manual (SingleR_1.1.6 ), I see a convenient option to provide references in a list and obtain cellular annotation with the top score across references. Since scores from only the first step are comparable (before fine.tuning) across references, then how are we able to obtain label.fine annotations in the output? Is the fine.tune step even executed when providing a list of references?
If possible, kindly share further details.

Code:
### setup reference datasets
list.ref <- list()
list.ref[["bp.encode"]] <- BlueprintEncodeData()
list.ref[["hpca"]] <- HumanPrimaryCellAtlasData()

### labels
list.labels <- lapply(list.ref, function(x) x$label.fine)

### run SingleR
pred  <- SingleR(test = SeuratObject@assays$SCT@counts, 
                 ref = list.ref, labels = list.labels, fine.tune = T)
Best,
Namit

**Comment by LTLA** [comment]
Consider reading `?combineResults`.

**Comment by namit-k** [comment]
We are using common.genes with multiple references as stated in combineResults, but still not clear if we are in fact executing the fine tuning step with multiple references?

If yes, how are the genes determined for the fine tuning step?
For instance, for a cell the top scores are in the order: celltypeA.ref1, celltypeB.ref2 .... Now, to find the genes used for the fine.tuning step, are we performing differential expression on  celltypeA.ref1-vs-celltypeB.ref2?

**Comment by LTLA** [comment]
> Now, to find the genes used for the fine.tuning step, are we performing differential expression on celltypeA.ref1-vs-celltypeB.ref2?

As described in `?combineResults`, this is Option 1. `combineResults` implements Option 3.
