### ISSUE TITLE
Problems with Annotating TSNEPlot for Seurat Object with SingleR

### ISSUE THREAD

**Issue by KBoostan** [LTLA/SingleR#82]
I have an object of class Seurat named Integration, consisting of 8 merged datasets from GSE 122960 IPF scRNA data, which I want to annotate with cell types using SingleR on the TSNE plot 
1). First, I converted my Seurat object, Integration, to a SingleCellExperiment, which I named Integration1 using the function as.SingleCellExperiment(Integration)
2). I am using the Immgen database to annotate my cells
3). I have successfully used the SingleR function to label my dataset with the reference dataset, Immgen. 
4). I am trying to use the TSNEPlot("labels", object)
 function to map the reference labels onto my integration TSNE plot

Here are my problems
1) The output TSNE plot that is generated has no labels
2) The "single" method usually works for SingleR, but when I use the "cluster" method, it says that I have to specify clusters, which I do not understand how to do.

I'll send in my code as a reference. Thank you!

![SingleR annotation ](https://user-images.githubusercontent.com/54972577/72213948-d1607400-34ac-11ea-8d1c-d8d08c57f094.png)

**Comment by j-andrews7** [comment]
Most of this isn't related to SingleR, rather being the result of not fully understanding Seurat functionality. I recommend reading their [manual](https://cran.r-project.org/web/packages/Seurat/Seurat.pdf) to figure out how to actually plot different metadata variables. 

As for your code, there are a few issues:

1. You never assign the labels back to your `Seurat` object, which can be done with something like:

   ```
   Integration[["SingleR.labels"]] <- pred.immgen$labels
   ```

2. Line 141 doesn't actually do anything, as you're assigning a variable to itself. It can be removed.

3. To provide clusters to the `SingleR` call, you need to pass your cluster metadata by setting `clusters = Integration1[["your.clusters"]]` to whatever your cluster column is named. You can explore your Seurat object or SingleCellExperiment object to determine the name that should replace "your.clusters".

   You can then assign the resulting labels back to your clusters with something like:

   ```
   Integration[["SingleR.cluster.labels"]] <- 
           pred.immgen$labels[match(Integration[[]][["your.clusters"]], rownames(pred.immgen))]
   ```

4. Lastly, your `TSNEPlot` call is incorrect. After performing step 1 above, you should get what you want with:

   ```
   TSNEPlot(Integration, group.by = "SingleR.labels")
   ```

**Comment by KBoostan** [comment]
Thank you, it worked! I really appreciate your help and I will look more closely at the Seurat manual.

**Comment by dtm2451** [comment]
Hello,

Great jobe getting this far!

1. `ref` is not used for Seurat's TSNEPlot in that way.  I think you mean to put `"pred.immgen$labels"` instead of `ref = "immgen$label.fine"` in line 149.  Or, if you want to run the function as you have listed in your "4)" you can add the labels as a metadata to your Seurat object, Integration.  You add it to the SingleCellExperiment version instead in line 148.

2. See `?Seurat::Idents`. To obtain the clusters from your Sumeurat object, the code is `Idents(seurat_object)`
  You can supply that to SingleR's cluster input.
