### ISSUE TITLE
could not find function "HumanPrimaryCellAtlasData"

### ISSUE THREAD

**Issue by yycunc** [LTLA/SingleR#85]
Hi there,
I am using SingleR to do cell annotation, but when loading the built reference Human Primary cell Atlas data, I met an error as follow:
> library(SingleR)
> hpca.se <- HumanPrimaryCellAtlasData()
Error in HumanPrimaryCellAtlasData() : 
  could not find function "HumanPrimaryCellAtlasData"

I have correctly install SingleR package. Could you tell me how to fix it?

**Comment by LTLA** [comment]
> I have correctly install SingleR package.

I doubt that. Follow the Bioconductor [installation instructions](https://bioconductor.org/packages/release/bioc/html/SingleR.html) and make sure you have version 1.0.*.

**Comment by yycunc** [comment]
Thanks for your response. 

I run sessionInfo()

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] SingleCellExperiment_1.8.0  SummarizedExperiment_1.16.0 DelayedArray_0.12.0        
 [4] BiocParallel_1.20.0         matrixStats_0.55.0          Biobase_2.46.0             
 [7] GenomicRanges_1.38.0        GenomeInfoDb_1.22.0         IRanges_2.20.1             
[10] S4Vectors_0.24.1            BiocGenerics_0.32.0         SingleR_1.0.1

**Comment by LTLA** [comment]
Upgrade to 1.0.7 and try again. We can't debug old versions anyway.

**Comment by yycunc** [comment]
What version of R does it required for 1.0.7? Now I use R/3.6.1. 

Thanks!

**Comment by LTLA** [comment]
Literally from the instructions in my link above:

> **Installation**
>
> To install this package, start R (version "3.6") and enter:

**Comment by yycunc** [comment]
I restart my computer and reinstall SingleR. Finally it works!

Thanks for your help!
