### ISSUE TITLE
Could I ask for a help?

### ISSUE THREAD

**Issue by Midsummer723** [LTLA/SingleR#88]
Could  I ask for a help please.
I want to show a table of original ident and singleR ref data which can show how the cells types in the different original files which are patients. ( If it can show the all labels in the ref like all different T cell types not just as T cell.
Thank you very much.

**Comment by LTLA** [comment]
I have absolutely no idea what you are asking, but the answer is probably "yes".

**Comment by j-andrews7** [comment]
Gonna need some clarification there. Can you provide an example?

**Comment by Midsummer723** [comment]
For example I have a file which is combined 10 patients data. I can use the original ident which is the number of the data.  I want show the cell types which from the ref database(example :the HumanPrimaryCellAtlasData). I want to make a table show the all the cell types in different data.

**Comment by Midsummer723** [comment]
And the cell type is not just as a T cell, but it can show all the cell type like use the" label.fine" not the "label.main".

**Comment by j-andrews7** [comment]
So you want to see cell counts for each cell type for each patient?

**Comment by Midsummer723** [comment]
Yes,
Thank you

**Comment by j-andrews7** [comment]
This is more just a general R question, but there are many options. Assuming you've assigned the labels to your metadata of whatever sort of single cell expression construct you're using (SCE, Seurat, whatever), this can be done with dplyr, base R, data.table, all sorts of things. 

The easiest way (in base R) is probably with `table`. As an example:

```
library(scRNAseq)

# A single cell experiment with some populated metadata.
hESCs <- LaMannoBrainData('human-es')
table(hESCs$Timepoint, hESCs$Cell_type)
```

This yields a table of cell types broken down by time point. This can be easily adapted to use your patient IDs in place of the time point.

**Comment by LTLA** [comment]
I'm going to assume that this was resolved.
