### ISSUE TITLE
approach to ExperimentHub usage

### ISSUE THREAD

**Issue by vjcitn** [LTLA/SingleR#89]
This pattern of querying ExperimentHub
```
    for (a in assays) {
        nrmcnts <- hub[hub$rdatapath == file.path(host, paste0(a, 
            ".rds"))][[1]]
        all.assays[[a]] <- .rm_NAs(nrmcnts, rm.NA)
    }
```
occurs a few times in .create_se.

It works, but the `[[1]]` is problematic.  I think the following approach to getting
the AH number would be better

```
names(query(hub, c(host, a)))
```
If you would like a pull request with this modification let me know.

**Comment by LTLA** [comment]
Six of one and half a dozen of the other. What's the advantage of the change? In fact, seems like a pattern match runs the risk of picking up things with the same `host` and `a` that isn't in the `rdatapath` - the entire `mcols` is searched, after all - whereas the current approach is exact.

**Comment by vjcitn** [comment]
The [[1]] makes an arbitrary selection in case multiple entities are returned from `hub[...]`.  But you have a point.  Similar bulletproofing would be needed for the proposed change.
