### ISSUE TITLE
elder version singleR package and current singleR package have different results

### ISSUE THREAD

**Issue by ww1021pp** [LTLA/SingleR#90]
Currently, I installed the new version SingleR Packages, and the function CreateSinglerObject() cannot run normally, and the the annotation results of new version SingleR annotation are different from the elder one(default parameters). So why are they not different?

**Comment by j-andrews7** [comment]
I'm confused. Are you asking why they aren't different? Or why they may have (very) slight differences? Or why the `CreateSinglerObject` funtion is no longer needed/used?

The methodology of both versions are very similar, though implementation has changed slightly to dramatically improve performance and simplify use. Differences should be very minor, though we do include label pruning for low confidence assignments and different label granularities.

The `CreateSinglerObject` function is no longer necessary, as we've simplified the inputs to `SingleR`. If you want to use your own reference, you just need a matrix of gene counts/samples and a list of labels for each sample. I'd recommend reading `?SingleR` and taking a [look at the vignette](https://bioconductor.org/packages/release/bioc/vignettes/SingleR/inst/doc/SingleR.html). They should answer any questions you have about the new version.

**Comment by ww1021pp** [comment]
Well. The results of current version and elder version are different. And I don't know what caused these differences with the same test and reference data.

**Comment by j-andrews7** [comment]
As I said, there may be fairly minor differences. Without a specific example, I can't say anything more.

**Comment by j-andrews7** [comment]
I'm going to assume this has been resolved. Feel free to reopen if you have a more specific example/issue to discuss.
