### ISSUE TITLE
plotScoreHeatmap - Colour Palette

### ISSUE THREAD

**Issue by TJonCooper** [LTLA/SingleR#91]
Ordinarily, when using _pheatmap_, I will construct a palette and pass it as an argument like this:

`pheatmap(pred.hesc,color = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral")))(1000))`

However, when using _plotScoreHeatMap_, the argument is accepted but ignored - and the plot still uses the default blue-yellow-green palette. 

_plotScoreHeatmap(pred.hesc,color = colorRampPalette(rev(brewer.pal(n = 11, name = "Spectral"))))_

Is this a bug? If not, what am I doing wrong?

**Comment by dtm2451** [comment]
I suppose this could be considered a bug in that we do intend for most pheatmap options to be adjustable by users.  The reason this isn't working for you is that color input is adjusted internally (a different palette is used for normalized = TRUE versus normalized = FALSE), so your supplied color input is getting replaced with ours.

I should be able to add a simple if statement to allow your colors to make it through.  @LTLA any reason you see NOT to allow users to change the colors?

**Comment by LTLA** [comment]
Why would there by any reason to replace perfection? :)

Just kidding. I've no problems with another argument. Just give it the same name as that in `pheatmap`. In terms of the internals, it seems easiest to let the function go about its business, and then override `$colors` with a non-`NULL` user-supplied one before the `pheatmap()` call.

**Comment by dtm2451** [comment]
Even simpler than that I believe, see #92.

`...` for the function is already meant for adjustment of pheatmap-specific inputs. So all we need is an "add ours if the user didn't already supply them".

**Comment by LTLA** [comment]
Unfortunately, `...` will support partial argument names, so checking `color` won't check `colo` or other substrings that might match. In general, it's safest to have an explicit argument if you plan to do anything other than passing the value along verbatim.
