### ISSUE TITLE
building references for SingleR

### ISSUE THREAD

**Issue by shatakshee1** [LTLA/SingleR#97]
Hello,

I have been able to successfully use SingleR with the pre-built references. But I was wondering if it is possible to build new references for use in SingleR. If yes, could you please help me understand how can I build new references for SingleR.

Thank you for your help,

Shatakshee Chatterjee

**Comment by j-andrews7** [comment]
Yes, this is quite easy. All you have to do is provide a log-transformed matrix with genes as rows and samples as columns containing counts. And then provide a vector of labels for each sample. This should be provided to the `ref` and `label` parameters of `SingleR`, respectively. Reading `?SingleR` will provide more info.

**Comment by j-andrews7** [comment]
I'm assuming this has addressed your issue. Feel free to re-open if you are still having trouble.
